/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import DAO.ChuyenDeDAO;
import Entity.ChuyenDe;
import Utils.Auth;
import Utils.MsgBox;
import Utils.XImage;
import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vietm
 */
public class ChuyenDe_Dialog extends java.awt.Dialog {

    /**
     * Creates new form ChuyenDee_Dialog
     */
    public ChuyenDe_Dialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        pnl_Center = new javax.swing.JPanel();
        lbl_Chuyende = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        pnl_Capnhat = new javax.swing.JPanel();
        lbl_Nhan = new javax.swing.JLabel();
        lbl_Hinh = new javax.swing.JLabel();
        lbl_Machuyende = new javax.swing.JLabel();
        txt_MaCD = new javax.swing.JTextField();
        lbl_Tenchuyende = new javax.swing.JLabel();
        txt_TenCD = new javax.swing.JTextField();
        lbl_Thoiluong = new javax.swing.JLabel();
        txt_Thoiluong = new javax.swing.JTextField();
        lbl_Hocphi = new javax.swing.JLabel();
        txt_Hocphi = new javax.swing.JTextField();
        lbl_Mota = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_Mota = new javax.swing.JTextArea();
        spr1 = new javax.swing.JSeparator();
        spr2 = new javax.swing.JSeparator();
        spr3 = new javax.swing.JSeparator();
        spr4 = new javax.swing.JSeparator();
        btn_Them = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Moi = new javax.swing.JButton();
        btn_First = new javax.swing.JButton();
        btn_Prev = new javax.swing.JButton();
        btn_Next = new javax.swing.JButton();
        btn_Last = new javax.swing.JButton();
        pnl_Danhsach = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Chuyende = new javax.swing.JTable();
        pnl_Chooser = new javax.swing.JPanel();
        fileChooser = new javax.swing.JFileChooser();

        setTitle("EduSys - QUẢN LÝ CHUYÊN ĐỀ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        pnl1.setBackground(new java.awt.Color(255, 255, 255));
        pnl1.setLayout(new java.awt.CardLayout());

        pnl_Center.setBackground(new java.awt.Color(255, 255, 255));

        lbl_Chuyende.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Chuyende.setForeground(new java.awt.Color(102, 102, 102));
        lbl_Chuyende.setText("  QUẢN LÝ CHUYÊN ĐỀ");

        tabs.setBackground(new java.awt.Color(255, 255, 255));
        tabs.setForeground(new java.awt.Color(255, 102, 102));
        tabs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        pnl_Capnhat.setBackground(new java.awt.Color(255, 255, 255));

        lbl_Nhan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_Nhan.setForeground(new java.awt.Color(102, 102, 102));
        lbl_Nhan.setText("Hình Logo");

        lbl_Hinh.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Hinh.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_Hinh.setForeground(new java.awt.Color(255, 102, 102));
        lbl_Hinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Hinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/image.png"))); // NOI18N
        lbl_Hinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        lbl_Hinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_HinhMouseClicked(evt);
            }
        });

        lbl_Machuyende.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_Machuyende.setForeground(new java.awt.Color(102, 102, 102));
        lbl_Machuyende.setText("Mã Chuyên Đề");

        txt_MaCD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_MaCD.setForeground(new java.awt.Color(255, 102, 102));
        txt_MaCD.setBorder(null);

        lbl_Tenchuyende.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_Tenchuyende.setForeground(new java.awt.Color(102, 102, 102));
        lbl_Tenchuyende.setText("Tên Chuyên Đề");

        txt_TenCD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_TenCD.setForeground(new java.awt.Color(255, 102, 102));
        txt_TenCD.setBorder(null);

        lbl_Thoiluong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_Thoiluong.setForeground(new java.awt.Color(102, 102, 102));
        lbl_Thoiluong.setText("Thời Lượng (Giờ)");

        txt_Thoiluong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_Thoiluong.setForeground(new java.awt.Color(255, 102, 102));
        txt_Thoiluong.setBorder(null);

        lbl_Hocphi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_Hocphi.setForeground(new java.awt.Color(102, 102, 102));
        lbl_Hocphi.setText("Học Phí");

        txt_Hocphi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_Hocphi.setForeground(new java.awt.Color(255, 102, 102));
        txt_Hocphi.setBorder(null);

        lbl_Mota.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_Mota.setForeground(new java.awt.Color(102, 102, 102));
        lbl_Mota.setText("Mô Tả Chuyên Đề");

        txt_Mota.setColumns(20);
        txt_Mota.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_Mota.setForeground(new java.awt.Color(255, 102, 102));
        txt_Mota.setRows(5);
        jScrollPane4.setViewportView(txt_Mota);

        spr1.setBackground(new java.awt.Color(102, 102, 102));
        spr1.setForeground(new java.awt.Color(102, 102, 102));

        spr2.setBackground(new java.awt.Color(102, 102, 102));
        spr2.setForeground(new java.awt.Color(102, 102, 102));

        spr3.setBackground(new java.awt.Color(102, 102, 102));
        spr3.setForeground(new java.awt.Color(102, 102, 102));

        spr4.setBackground(new java.awt.Color(102, 102, 102));
        spr4.setForeground(new java.awt.Color(102, 102, 102));

        btn_Them.setBackground(new java.awt.Color(102, 102, 102));
        btn_Them.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Them.setForeground(new java.awt.Color(255, 255, 255));
        btn_Them.setText("Thêm");
        btn_Them.setBorder(null);
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Sua.setBackground(new java.awt.Color(102, 102, 102));
        btn_Sua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_Sua.setText("Sửa");
        btn_Sua.setBorder(null);
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Xoa.setBackground(new java.awt.Color(102, 102, 102));
        btn_Xoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_Xoa.setText("Xóa");
        btn_Xoa.setBorder(null);
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_Moi.setBackground(new java.awt.Color(102, 102, 102));
        btn_Moi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Moi.setForeground(new java.awt.Color(255, 255, 255));
        btn_Moi.setText("Mới");
        btn_Moi.setBorder(null);
        btn_Moi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MoiActionPerformed(evt);
            }
        });

        btn_First.setBackground(new java.awt.Color(102, 102, 102));
        btn_First.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_First.setForeground(new java.awt.Color(255, 255, 255));
        btn_First.setText("|<");
        btn_First.setBorder(null);
        btn_First.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FirstActionPerformed(evt);
            }
        });

        btn_Prev.setBackground(new java.awt.Color(102, 102, 102));
        btn_Prev.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Prev.setForeground(new java.awt.Color(255, 255, 255));
        btn_Prev.setText("<<");
        btn_Prev.setBorder(null);
        btn_Prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrevActionPerformed(evt);
            }
        });

        btn_Next.setBackground(new java.awt.Color(102, 102, 102));
        btn_Next.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Next.setForeground(new java.awt.Color(255, 255, 255));
        btn_Next.setText(">>");
        btn_Next.setBorder(null);
        btn_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NextActionPerformed(evt);
            }
        });

        btn_Last.setBackground(new java.awt.Color(102, 102, 102));
        btn_Last.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Last.setForeground(new java.awt.Color(255, 255, 255));
        btn_Last.setText(">|");
        btn_Last.setBorder(null);
        btn_Last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_CapnhatLayout = new javax.swing.GroupLayout(pnl_Capnhat);
        pnl_Capnhat.setLayout(pnl_CapnhatLayout);
        pnl_CapnhatLayout.setHorizontalGroup(
            pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                        .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Moi, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_First, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Prev, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Last, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4)
                    .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                        .addComponent(lbl_Mota)
                        .addGap(103, 103, 103)
                        .addComponent(spr4))
                    .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                        .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Nhan)
                            .addComponent(lbl_Hinh, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(spr3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Thoiluong, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spr2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_TenCD, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spr1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Machuyende, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Tenchuyende, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Thoiluong, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Hocphi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_MaCD, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Hocphi, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_CapnhatLayout.setVerticalGroup(
            pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Nhan)
                    .addComponent(lbl_Machuyende))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                        .addComponent(txt_MaCD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(spr1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(lbl_Tenchuyende)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_TenCD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(spr2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Thoiluong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Thoiluong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(spr3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(lbl_Hocphi)
                        .addGap(12, 12, 12)
                        .addComponent(txt_Hocphi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_Hinh, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_Mota))
                    .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(spr4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Moi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_First, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Prev, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Last, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("Cập Nhật", pnl_Capnhat);

        pnl_Danhsach.setBackground(new java.awt.Color(255, 255, 255));

        tbl_Chuyende.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_Chuyende.setForeground(new java.awt.Color(102, 102, 102));
        tbl_Chuyende.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã CD", "Tên CD", "Học Phí", "Thời Lượng", "Hình"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Chuyende.setRowHeight(22);
        tbl_Chuyende.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_Chuyende.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_Chuyende.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ChuyendeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Chuyende);

        javax.swing.GroupLayout pnl_DanhsachLayout = new javax.swing.GroupLayout(pnl_Danhsach);
        pnl_Danhsach.setLayout(pnl_DanhsachLayout);
        pnl_DanhsachLayout.setHorizontalGroup(
            pnl_DanhsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
        );
        pnl_DanhsachLayout.setVerticalGroup(
            pnl_DanhsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        tabs.addTab("Danh Sách", pnl_Danhsach);

        javax.swing.GroupLayout pnl_CenterLayout = new javax.swing.GroupLayout(pnl_Center);
        pnl_Center.setLayout(pnl_CenterLayout);
        pnl_CenterLayout.setHorizontalGroup(
            pnl_CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CenterLayout.createSequentialGroup()
                .addGroup(pnl_CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Chuyende, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnl_CenterLayout.setVerticalGroup(
            pnl_CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CenterLayout.createSequentialGroup()
                .addComponent(lbl_Chuyende)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabs))
        );

        pnl1.add(pnl_Center, "card2");

        pnl_Chooser.setBackground(new java.awt.Color(255, 255, 255));

        fileChooser.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout pnl_ChooserLayout = new javax.swing.GroupLayout(pnl_Chooser);
        pnl_Chooser.setLayout(pnl_ChooserLayout);
        pnl_ChooserLayout.setHorizontalGroup(
            pnl_ChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ChooserLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pnl_ChooserLayout.setVerticalGroup(
            pnl_ChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ChooserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pnl1.add(pnl_Chooser, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void lbl_HinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HinhMouseClicked
        // TODO add your handling code here:
        this.chonAnh();
    }//GEN-LAST:event_lbl_HinhMouseClicked

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        this.insert();
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_MoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MoiActionPerformed
        // TODO add your handling code here:
        this.clearForm();
    }//GEN-LAST:event_btn_MoiActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_FirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FirstActionPerformed
        // TODO add your handling code here:
        this.first();
    }//GEN-LAST:event_btn_FirstActionPerformed

    private void btn_PrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrevActionPerformed
        // TODO add your handling code here:
        this.prev();
    }//GEN-LAST:event_btn_PrevActionPerformed

    private void btn_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NextActionPerformed
        // TODO add your handling code here:
        this.next();
    }//GEN-LAST:event_btn_NextActionPerformed

    private void btn_LastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LastActionPerformed
        // TODO add your handling code here:
        this.last();
    }//GEN-LAST:event_btn_LastActionPerformed

    private void tbl_ChuyendeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ChuyendeMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            this.row = tbl_Chuyende.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tbl_ChuyendeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChuyenDe_Dialog dialog = new ChuyenDe_Dialog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_First;
    private javax.swing.JButton btn_Last;
    private javax.swing.JButton btn_Moi;
    private javax.swing.JButton btn_Next;
    private javax.swing.JButton btn_Prev;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_Chuyende;
    private javax.swing.JLabel lbl_Hinh;
    private javax.swing.JLabel lbl_Hocphi;
    private javax.swing.JLabel lbl_Machuyende;
    private javax.swing.JLabel lbl_Mota;
    private javax.swing.JLabel lbl_Nhan;
    private javax.swing.JLabel lbl_Tenchuyende;
    private javax.swing.JLabel lbl_Thoiluong;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl_Capnhat;
    private javax.swing.JPanel pnl_Center;
    private javax.swing.JPanel pnl_Chooser;
    private javax.swing.JPanel pnl_Danhsach;
    private javax.swing.JSeparator spr1;
    private javax.swing.JSeparator spr2;
    private javax.swing.JSeparator spr3;
    private javax.swing.JSeparator spr4;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tbl_Chuyende;
    private javax.swing.JTextField txt_Hocphi;
    private javax.swing.JTextField txt_MaCD;
    private javax.swing.JTextArea txt_Mota;
    private javax.swing.JTextField txt_TenCD;
    private javax.swing.JTextField txt_Thoiluong;
    // End of variables declaration//GEN-END:variables

    ChuyenDeDAO dao = new ChuyenDeDAO();
    int row = -1;

    private void init() {
        //chuyển Dialog ra giữa màn hình
        this.setLocationRelativeTo(null);
        // gọi hàm tạo icon tiêu đề cho frame
        this.setIconImage(XImage.getAppIcon());
        this.fillTable();
        this.row = -1;
        this.updateStatus();
        clearForm();
    }

    private void insert() {
        ChuyenDe cd = getForm();
        String maCD = txt_MaCD.getText();
        String tenCD = txt_TenCD.getText();
        String moTa = txt_Mota.getText();
        if (!Auth.isManager()) {
            MsgBox.warning(this, "Bạn Không Thể Thêm Chuyên Đề !");
        } else if (maCD.equals("") || tenCD.equals("") || moTa.equals("")) {
            MsgBox.warning(this, "Thông Tin Chuyên Đề Còn Trống !");
        } else {
            try {
                dao.insert(cd);
                this.clearForm();
                this.fillTable();
                lbl_Hinh.setIcon(null);
                MsgBox.alert(this, "Thêm Thành Công");
            } catch (Exception e) {
                MsgBox.warning(this, "Vui Lòng Chọn Ảnh (Bắt Buộc) !");
            }
        }
    }

    private void update() {
        ChuyenDe cd = getForm();
        try {
            dao.update(cd);
            this.fillTable();
            MsgBox.alert(this, "Cập Nhật Thành Công");
        } catch (Exception e) {
            MsgBox.warning(this, "Cập Nhật Thất Bại !");
        }
    }

    private void delete() {
        if (!Auth.isManager()) {
            MsgBox.warning(this, "Bạn Không Có Quyền Xóa Chuyên Đề !");
        } else {
            if (MsgBox.confirm(this, "Xóa Chuyên Đề Này ?")) {
                String macd = txt_MaCD.getText();
                try {
                    dao.delete(macd);
                    this.fillTable();
                    this.clearForm();
                    lbl_Hinh.setIcon(null);
                    MsgBox.alert(this, "Xóa Thành Công");
                } catch (Exception e) {
                    MsgBox.warning(this, "Xóa Thất Bại !");
                }
            }
        }
    }

    private void edit() {
        String macd = (String) tbl_Chuyende.getValueAt(this.row, 0);
        ChuyenDe cd = dao.selectById(macd);
        this.setForm(cd);
        tabs.setSelectedIndex(0);
        this.updateStatus();
    }

    private void first() {
        this.row = 0;
        this.edit();
    }

    private void prev() {
        if (this.row > 0) {
            this.row--;
            this.edit();
        }
    }

    private void next() {
        if (this.row < tbl_Chuyende.getRowCount() - 1) {
            this.row++;
            this.edit();
        }
    }

    private void last() {
        this.row = tbl_Chuyende.getRowCount() - 1;
        this.edit();
    }

    private void fillTable() {
        DefaultTableModel dtm = (DefaultTableModel) tbl_Chuyende.getModel();
        dtm.setRowCount(0);//xóa hết các hàng trong bảng
        try {
            List<ChuyenDe> list = dao.selectAll();//đọc data từ sql
            for (ChuyenDe cd : list) {
                Object[] row = {cd.getMaCD(), cd.getTenCD(), cd.getHocPhi(), cd.getThoiLuong(), cd.getHinh()};
                dtm.addRow(row);//thêm vào table dòng
            }
        } catch (Exception e) {
            MsgBox.warning(this, "Lỗi Truy Vấn Dữ Liệu !");
        }
    }

    private void setForm(ChuyenDe cd) {
        txt_MaCD.setText(cd.getMaCD());
        txt_TenCD.setText(cd.getTenCD());
        txt_Thoiluong.setText(String.valueOf(cd.getThoiLuong()));
        txt_Hocphi.setText(String.valueOf(cd.getHocPhi()));
        txt_Mota.setText(cd.getMoTa());
        if (cd.getHinh() != null) {
            lbl_Hinh.setToolTipText(cd.getHinh());
            lbl_Hinh.setIcon(XImage.read(cd.getHinh()));
        }
    }

    ChuyenDe getForm() {
        ChuyenDe cd = new ChuyenDe();
        cd.setMaCD(txt_MaCD.getText());
        cd.setTenCD(txt_TenCD.getText());
        cd.setThoiLuong(Integer.valueOf(txt_Thoiluong.getText()));
        cd.setHocPhi(Double.valueOf(txt_Hocphi.getText()));
        cd.setMoTa(txt_Mota.getText());
        cd.setHinh(lbl_Hinh.getToolTipText());
        return cd;
    }

    private void clearForm() {
        ChuyenDe cd = new ChuyenDe();
        this.setForm(cd);
        this.row = -1;
        this.updateStatus();
    }

    private void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tbl_Chuyende.getRowCount() - 1);
        //trạng thai form
        txt_MaCD.setEditable(!edit);
        btn_Them.setEnabled(!edit);
        btn_Sua.setEnabled(edit);
        btn_Xoa.setEnabled(edit);
        //trạng thái diều hướng
        btn_First.setEnabled(edit && !first);
        btn_Prev.setEnabled(edit && !first);
        btn_Next.setEnabled(edit && !last);
        btn_Last.setEnabled(edit && !last);
    }

    private void chonAnh() {
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            XImage.save(file);//lưu ảnh vào thư mục logos
            ImageIcon icon = XImage.read(file.getName());//đọc hình từ logos
            lbl_Hinh.setIcon(icon);
            lbl_Hinh.setToolTipText(file.getName());//lưu tên hình trong tooltip
        }
    }
}
