/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import Entity.NhanVien;
import Utils.XImage;
import Utils.Auth;
import Utils.MsgBox;
import DAO.NhanVienDAO;

/**
 *
 * @author vietm
 */
public class DangNhap_Dialog extends java.awt.Dialog {

    /**
     * Creates new form Login_dialog
     */
    public DangNhap_Dialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    NhanVienDAO dao = new NhanVienDAO();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        pnl2 = new javax.swing.JPanel();
        pnl_Login = new javax.swing.JPanel();
        txt_User = new javax.swing.JTextField();
        spr1 = new javax.swing.JSeparator();
        spr2 = new javax.swing.JSeparator();
        lbl_Pwd = new javax.swing.JLabel();
        lbl_User = new javax.swing.JLabel();
        lbl_Login = new javax.swing.JLabel();
        lbl_Logo = new javax.swing.JLabel();
        txt_Pwd = new javax.swing.JPasswordField();
        lbl_FogotPwd = new javax.swing.JLabel();
        btn_Login = new javax.swing.JButton();
        pnl_Loader = new javax.swing.JPanel();
        lbl_Loading = new javax.swing.JLabel();
        lbl_Logginin = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationRelativeTo(null);
        setTitle("EduSys - login");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        pnl1.setBackground(new java.awt.Color(255, 255, 255));

        pnl2.setBackground(new java.awt.Color(255, 255, 255));
        pnl2.setLayout(new java.awt.CardLayout());

        pnl_Login.setBackground(new java.awt.Color(255, 255, 255));

        txt_User.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_User.setForeground(new java.awt.Color(102, 102, 102));
        txt_User.setText("User");
        txt_User.setBorder(null);
        txt_User.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_UserFocusGained(evt);
            }
        });

        spr1.setBackground(new java.awt.Color(41, 168, 73));
        spr1.setForeground(new java.awt.Color(41, 168, 73));

        spr2.setBackground(new java.awt.Color(41, 168, 73));
        spr2.setForeground(new java.awt.Color(41, 168, 73));

        lbl_Pwd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Pwd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Unlock-3-icon.png"))); // NOI18N

        lbl_User.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/112-group-icon.png"))); // NOI18N

        lbl_Login.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        lbl_Login.setForeground(new java.awt.Color(51, 51, 51));
        lbl_Login.setText("Login");

        lbl_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo_FPT.png"))); // NOI18N

        txt_Pwd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Pwd.setForeground(new java.awt.Color(102, 102, 102));
        txt_Pwd.setText("jPasswordField1");
        txt_Pwd.setBorder(null);
        txt_Pwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_PwdFocusGained(evt);
            }
        });

        lbl_FogotPwd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_FogotPwd.setForeground(new java.awt.Color(51, 51, 51));
        lbl_FogotPwd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_FogotPwd.setText("Forgot password ?");
        lbl_FogotPwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_FogotPwdMouseClicked(evt);
            }
        });

        btn_Login.setBackground(new java.awt.Color(41, 168, 73));
        btn_Login.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Login.setForeground(new java.awt.Color(255, 255, 255));
        btn_Login.setText("Login");
        btn_Login.setBorder(null);
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_LoginLayout = new javax.swing.GroupLayout(pnl_Login);
        pnl_Login.setLayout(pnl_LoginLayout);
        pnl_LoginLayout.setHorizontalGroup(
            pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_LoginLayout.createSequentialGroup()
                .addGroup(pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_LoginLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lbl_Login)
                        .addGap(122, 122, 122)
                        .addComponent(lbl_Logo))
                    .addGroup(pnl_LoginLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lbl_User)
                        .addGap(13, 13, 13)
                        .addGroup(pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_User, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spr1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_LoginLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lbl_Pwd)
                        .addGap(10, 10, 10)
                        .addComponent(txt_Pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_LoginLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(spr2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_LoginLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(lbl_FogotPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
        );
        pnl_LoginLayout.setVerticalGroup(
            pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_LoginLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_LoginLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lbl_User, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_LoginLayout.createSequentialGroup()
                        .addComponent(txt_User, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(spr1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_LoginLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lbl_Pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_Pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(spr2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnl_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_LoginLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lbl_FogotPwd)
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_LoginLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );

        pnl2.add(pnl_Login, "card2");

        pnl_Loader.setBackground(new java.awt.Color(255, 255, 255));

        lbl_Loading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ring.gif"))); // NOI18N

        lbl_Logginin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_Logginin.setForeground(new java.awt.Color(41, 168, 73));
        lbl_Logginin.setText("Loggin in...");

        javax.swing.GroupLayout pnl_LoaderLayout = new javax.swing.GroupLayout(pnl_Loader);
        pnl_Loader.setLayout(pnl_LoaderLayout);
        pnl_LoaderLayout.setHorizontalGroup(
            pnl_LoaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_LoaderLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(pnl_LoaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_Loading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_Logginin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        pnl_LoaderLayout.setVerticalGroup(
            pnl_LoaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_LoaderLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lbl_Loading)
                .addGap(18, 18, 18)
                .addComponent(lbl_Logginin)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pnl2.add(pnl_Loader, "card3");

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void txt_UserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_UserFocusGained
        // TODO add your handling code here:
        txt_User.setText("");
    }//GEN-LAST:event_txt_UserFocusGained

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
        // TODO add your handling code here:
        this.dangNhap();
    }//GEN-LAST:event_btn_LoginActionPerformed

    private void txt_PwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_PwdFocusGained
        // TODO add your handling code here:
        txt_Pwd.setText("");
    }//GEN-LAST:event_txt_PwdFocusGained

    private void lbl_FogotPwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_FogotPwdMouseClicked
        // TODO add your handling code here:
        this.forgotPwd();
    }//GEN-LAST:event_lbl_FogotPwdMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangNhap_Dialog dialog = new DangNhap_Dialog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Login;
    private javax.swing.JLabel lbl_FogotPwd;
    private javax.swing.JLabel lbl_Loading;
    private javax.swing.JLabel lbl_Logginin;
    private javax.swing.JLabel lbl_Login;
    private javax.swing.JLabel lbl_Logo;
    private javax.swing.JLabel lbl_Pwd;
    private javax.swing.JLabel lbl_User;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl_Loader;
    private javax.swing.JPanel pnl_Login;
    private javax.swing.JSeparator spr1;
    private javax.swing.JSeparator spr2;
    private javax.swing.JPasswordField txt_Pwd;
    private javax.swing.JTextField txt_User;
    // End of variables declaration//GEN-END:variables

    private void init() {
        //chuyển Dialog ra giữa màn hình
        this.setLocationRelativeTo(null);
        //gọi hàm tạo icon tiêu đề cho frame
        this.setIconImage(XImage.getAppIcon());
    }

    void dangNhap() {
        String manv = txt_User.getText();
        String matKhau = new String(txt_Pwd.getPassword());
        NhanVien nhanVien = dao.selectById(manv);
        if (nhanVien == null) {
            MsgBox.warning(this, "Sai Tên Đăng Nhập !");
        } else if (!matKhau.equals(nhanVien.getMatKhau())) {
            MsgBox.warning(this, "Sai Mật Khẩu !");
        } else {
            Auth.user = nhanVien;
            loading();
        }
    }

    private void loading() {
        Thread T = new Thread() {
            @Override
            public void run() {
                try {
                    for (int i = 0; i <= 1; i++) {
                        Thread.sleep(1000);
                        pnl_Login.hide();
                        pnl_Loader.show();
                        if (i == 1) {
                            DangNhap_Dialog.this.dispose();
                        }
                    }
                } catch (Exception e) {
                }
            }
        };
        T.start();
    }

    private void forgotPwd() {
        int i = 0;
        while (i == 0) {
            String user = MsgBox.prompt(this, "Vui Lòng Nhập Đúng Để Qua Bước Này\nNhập User :");
            NhanVien nhanVien = dao.selectById(user);
            if (nhanVien == null) {
                MsgBox.warning(this, "Sai User !");
            } else {
                String mk = MsgBox.prompt(this, "Nhập Mật Khẩu mới :");
                i = -1;
                while (i == -1) {
                    String mk1 = mk;
                    String mk2 = MsgBox.prompt(this, "Xác Nhận Mật Khẩu Mới :");
                    if (!mk1.equals(mk2)) {
                        MsgBox.warning(this, "Xác Nhận Mật Khẩu Không Chính Xác !");
                    } else {
                        NhanVien nv = new NhanVien();
                        nv.setMatKhau(mk1);
                        nv.setMaNV(user);
                        dao.updatee(nv);
                        MsgBox.alert(this, "Cập Nhật Mật Khẩu Thành Công");
                        i = 1;
                    }
                }
                i = 1;
            }
        }
    }
}
