/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import Utils.Auth;
import Utils.MsgBox;
import Utils.XImage;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author vietm
 */
public class EduSys_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Main_Frame
     */
    public EduSys_Frame() {
        initComponents();
        dongHo();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        pnl_Slide = new javax.swing.JPanel();
        lbl_Hocvien = new javax.swing.JLabel();
        lbl_Khoahoc = new javax.swing.JLabel();
        lbl_Dangxuat = new javax.swing.JLabel();
        lbl_Nguoihoc = new javax.swing.JLabel();
        lbl_Ketthuc = new javax.swing.JLabel();
        lbl_Chuyende = new javax.swing.JLabel();
        lbl_Huongdan = new javax.swing.JLabel();
        pnl_Center = new javax.swing.JPanel();
        lbl_Dongho = new javax.swing.JLabel();
        lbl_TextQuanlyDT = new javax.swing.JLabel();
        pnl_Images = new javax.swing.JPanel();
        lbl_Images = new javax.swing.JLabel();
        mnb = new javax.swing.JMenuBar();
        mnu_Hethong = new javax.swing.JMenu();
        mni_Dangxuat = new javax.swing.JMenuItem();
        spr1 = new javax.swing.JPopupMenu.Separator();
        mni_DoiMK = new javax.swing.JMenuItem();
        spr2 = new javax.swing.JPopupMenu.Separator();
        mni_Thoat = new javax.swing.JMenuItem();
        mnu_Quanly = new javax.swing.JMenu();
        mni_Chuyende = new javax.swing.JMenuItem();
        mni_Khoahoc = new javax.swing.JMenuItem();
        mni_Nguoihoc = new javax.swing.JMenuItem();
        mni_Hocvien = new javax.swing.JMenuItem();
        spr = new javax.swing.JPopupMenu.Separator();
        mni_QuanLyNV = new javax.swing.JMenuItem();
        mnu_Thongke = new javax.swing.JMenu();
        mni_Bangdiem = new javax.swing.JMenuItem();
        spr3 = new javax.swing.JPopupMenu.Separator();
        mn_LuongNH = new javax.swing.JMenuItem();
        mni_DiemCD = new javax.swing.JMenuItem();
        mni_Doanhthu = new javax.swing.JMenuItem();
        mnu_Trogiup = new javax.swing.JMenu();
        mni_HDSD = new javax.swing.JMenuItem();
        spr4 = new javax.swing.JPopupMenu.Separator();
        mni_Gioithieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EduSys - HỆ THỐNG QUẢN LÝ ĐÀO TẠO");

        pnl1.setBackground(new java.awt.Color(255, 255, 255));
        pnl1.setLayout(new java.awt.BorderLayout());

        pnl_Slide.setBackground(new java.awt.Color(102, 102, 102));
        pnl_Slide.setPreferredSize(new java.awt.Dimension(110, 0));

        lbl_Hocvien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Hocvien.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Hocvien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Hocvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Graduate-32px.png"))); // NOI18N
        lbl_Hocvien.setText("Học Viên");
        lbl_Hocvien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_Hocvien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbl_Hocvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_HocvienMouseClicked(evt);
            }
        });

        lbl_Khoahoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Khoahoc.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Khoahoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Khoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/course.png"))); // NOI18N
        lbl_Khoahoc.setText("Khóa Học");
        lbl_Khoahoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_Khoahoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbl_Khoahoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_KhoahocMouseClicked(evt);
            }
        });

        lbl_Dangxuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Dangxuat.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Dangxuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Dangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Computer-Lock-32px.png"))); // NOI18N
        lbl_Dangxuat.setText("Đăng Xuất");
        lbl_Dangxuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_Dangxuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbl_Dangxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_DangxuatMouseClicked(evt);
            }
        });

        lbl_Nguoihoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Nguoihoc.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nguoihoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Nguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/people.png"))); // NOI18N
        lbl_Nguoihoc.setText("Người Học");
        lbl_Nguoihoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_Nguoihoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbl_Nguoihoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_NguoihocMouseClicked(evt);
            }
        });

        lbl_Ketthuc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Ketthuc.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Ketthuc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Ketthuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/out.png"))); // NOI18N
        lbl_Ketthuc.setText("Kết Thúc");
        lbl_Ketthuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_Ketthuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbl_Ketthuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_KetthucMouseClicked(evt);
            }
        });

        lbl_Chuyende.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Chuyende.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Chuyende.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Chuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Documents-icon.png"))); // NOI18N
        lbl_Chuyende.setText("Chuyên Đề");
        lbl_Chuyende.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_Chuyende.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbl_Chuyende.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ChuyendeMouseClicked(evt);
            }
        });

        lbl_Huongdan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Huongdan.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Huongdan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Huongdan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/help.png"))); // NOI18N
        lbl_Huongdan.setText("Hướng Dẫn");
        lbl_Huongdan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_Huongdan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbl_Huongdan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_HuongdanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_SlideLayout = new javax.swing.GroupLayout(pnl_Slide);
        pnl_Slide.setLayout(pnl_SlideLayout);
        pnl_SlideLayout.setHorizontalGroup(
            pnl_SlideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_SlideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_SlideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Hocvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_Khoahoc, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(lbl_Dangxuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(lbl_Ketthuc, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(lbl_Chuyende, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(lbl_Nguoihoc, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(lbl_Huongdan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_SlideLayout.setVerticalGroup(
            pnl_SlideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_SlideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Dangxuat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Ketthuc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Chuyende)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Nguoihoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Khoahoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Hocvien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Huongdan)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pnl1.add(pnl_Slide, java.awt.BorderLayout.WEST);

        pnl_Center.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Center.setPreferredSize(new java.awt.Dimension(740, 479));

        lbl_Dongho.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Dongho.setForeground(new java.awt.Color(102, 102, 102));
        lbl_Dongho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clock-24px.png"))); // NOI18N
        lbl_Dongho.setText("00:00:00 CH");

        lbl_TextQuanlyDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_TextQuanlyDT.setForeground(new java.awt.Color(102, 102, 102));
        lbl_TextQuanlyDT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Info.png"))); // NOI18N
        lbl_TextQuanlyDT.setText("Hệ Quản Lý Đào Tạo");
        lbl_TextQuanlyDT.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        pnl_Images.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Images.setLayout(new java.awt.BorderLayout());

        lbl_Images.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Images.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Images.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/thiet-ke-web-da-nang1.png"))); // NOI18N
        lbl_Images.setToolTipText("");
        pnl_Images.add(lbl_Images, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnl_CenterLayout = new javax.swing.GroupLayout(pnl_Center);
        pnl_Center.setLayout(pnl_CenterLayout);
        pnl_CenterLayout.setHorizontalGroup(
            pnl_CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CenterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_Dongho)
                .addContainerGap())
            .addComponent(pnl_Images, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_CenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_TextQuanlyDT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_CenterLayout.setVerticalGroup(
            pnl_CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CenterLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lbl_Dongho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Images, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_TextQuanlyDT)
                .addGap(6, 6, 6))
        );

        pnl1.add(pnl_Center, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnl1, java.awt.BorderLayout.CENTER);

        mnb.setBackground(new java.awt.Color(255, 255, 255));

        mnu_Hethong.setBackground(new java.awt.Color(255, 255, 255));
        mnu_Hethong.setText("Hệ Thống");
        mnu_Hethong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        mni_Dangxuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mni_Dangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Computer-Lock-32px.png"))); // NOI18N
        mni_Dangxuat.setText("Đăng Xuất");
        mni_Dangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_DangxuatActionPerformed(evt);
            }
        });
        mnu_Hethong.add(mni_Dangxuat);
        mnu_Hethong.add(spr1);

        mni_DoiMK.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mni_DoiMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Settings-icon.png"))); // NOI18N
        mni_DoiMK.setText("Đổi Mật Khẩu");
        mni_DoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_DoiMKActionPerformed(evt);
            }
        });
        mnu_Hethong.add(mni_DoiMK);
        mnu_Hethong.add(spr2);

        mni_Thoat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mni_Thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/out.png"))); // NOI18N
        mni_Thoat.setText("Kết Thúc");
        mni_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_ThoatActionPerformed(evt);
            }
        });
        mnu_Hethong.add(mni_Thoat);

        mnb.add(mnu_Hethong);

        mnu_Quanly.setBackground(new java.awt.Color(255, 255, 255));
        mnu_Quanly.setText("Quản Lý");
        mnu_Quanly.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        mni_Chuyende.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mni_Chuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Documents-icon.png"))); // NOI18N
        mni_Chuyende.setText("Chuyên Đề");
        mni_Chuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_ChuyendeActionPerformed(evt);
            }
        });
        mnu_Quanly.add(mni_Chuyende);

        mni_Khoahoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mni_Khoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/course.png"))); // NOI18N
        mni_Khoahoc.setText("Khóa Học");
        mni_Khoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_KhoahocActionPerformed(evt);
            }
        });
        mnu_Quanly.add(mni_Khoahoc);

        mni_Nguoihoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mni_Nguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/people.png"))); // NOI18N
        mni_Nguoihoc.setText("Người Học");
        mni_Nguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_NguoihocActionPerformed(evt);
            }
        });
        mnu_Quanly.add(mni_Nguoihoc);

        mni_Hocvien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mni_Hocvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Graduate-32px.png"))); // NOI18N
        mni_Hocvien.setText("Học Viên");
        mni_Hocvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_HocvienActionPerformed(evt);
            }
        });
        mnu_Quanly.add(mni_Hocvien);
        mnu_Quanly.add(spr);

        mni_QuanLyNV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mni_QuanLyNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Groups.png"))); // NOI18N
        mni_QuanLyNV.setText("Quản Lý Nhân Viên");
        mni_QuanLyNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_QuanLyNVActionPerformed(evt);
            }
        });
        mnu_Quanly.add(mni_QuanLyNV);

        mnb.add(mnu_Quanly);

        mnu_Thongke.setBackground(new java.awt.Color(255, 255, 255));
        mnu_Thongke.setText("Thống Kê");
        mnu_Thongke.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        mni_Bangdiem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mni_Bangdiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/table-point.png"))); // NOI18N
        mni_Bangdiem.setText("Bảng Điểm");
        mni_Bangdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_BangdiemActionPerformed(evt);
            }
        });
        mnu_Thongke.add(mni_Bangdiem);
        mnu_Thongke.add(spr3);

        mn_LuongNH.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mn_LuongNH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Apps-preferences-contact-list-icon.png"))); // NOI18N
        mn_LuongNH.setText("Lượng Người Học");
        mn_LuongNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_LuongNHActionPerformed(evt);
            }
        });
        mnu_Thongke.add(mn_LuongNH);

        mni_DiemCD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mni_DiemCD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/numbers-icon.png"))); // NOI18N
        mni_DiemCD.setText("Điểm Chuyên Đề");
        mni_DiemCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_DiemCDActionPerformed(evt);
            }
        });
        mnu_Thongke.add(mni_DiemCD);

        mni_Doanhthu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mni_Doanhthu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Money-icon.png"))); // NOI18N
        mni_Doanhthu.setText("Doanh Thu");
        mni_Doanhthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_DoanhthuActionPerformed(evt);
            }
        });
        mnu_Thongke.add(mni_Doanhthu);

        mnb.add(mnu_Thongke);

        mnu_Trogiup.setBackground(new java.awt.Color(255, 255, 255));
        mnu_Trogiup.setText("Trợ Giúp");
        mnu_Trogiup.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        mni_HDSD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mni_HDSD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/help.png"))); // NOI18N
        mni_HDSD.setText("Hướng Dẫn Sử Dụng");
        mni_HDSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_HDSDActionPerformed(evt);
            }
        });
        mnu_Trogiup.add(mni_HDSD);
        mnu_Trogiup.add(spr4);

        mni_Gioithieu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mni_Gioithieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/about.png"))); // NOI18N
        mni_Gioithieu.setText("Giới Thiệu Sản Phẩm");
        mni_Gioithieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_GioithieuActionPerformed(evt);
            }
        });
        mnu_Trogiup.add(mni_Gioithieu);

        mnb.add(mnu_Trogiup);

        setJMenuBar(mnb);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mni_DangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_DangxuatActionPerformed
        // TODO add your handling code here:
        this.openDangXuat();
    }//GEN-LAST:event_mni_DangxuatActionPerformed

    private void lbl_DangxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_DangxuatMouseClicked
        // TODO add your handling code here:
        this.openDangXuat();
    }//GEN-LAST:event_lbl_DangxuatMouseClicked

    private void mni_DoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_DoiMKActionPerformed
        // TODO add your handling code here:
        this.openDoiMatKhau();
    }//GEN-LAST:event_mni_DoiMKActionPerformed

    private void mni_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_ThoatActionPerformed
        // TODO add your handling code here:
        this.ketThuc();
    }//GEN-LAST:event_mni_ThoatActionPerformed

    private void lbl_KetthucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_KetthucMouseClicked
        // TODO add your handling code here:
        this.ketThuc();
    }//GEN-LAST:event_lbl_KetthucMouseClicked

    private void mni_ChuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_ChuyendeActionPerformed
        // TODO add your handling code here:
        this.openChuyenDe();
    }//GEN-LAST:event_mni_ChuyendeActionPerformed

    private void lbl_ChuyendeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ChuyendeMouseClicked
        // TODO add your handling code here:
        this.openChuyenDe();
    }//GEN-LAST:event_lbl_ChuyendeMouseClicked

    private void mni_KhoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_KhoahocActionPerformed
        // TODO add your handling code here:
        this.openKhoaHoc();
    }//GEN-LAST:event_mni_KhoahocActionPerformed

    private void lbl_KhoahocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_KhoahocMouseClicked
        // TODO add your handling code here:
        this.openKhoaHoc();
    }//GEN-LAST:event_lbl_KhoahocMouseClicked

    private void mni_NguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_NguoihocActionPerformed
        // TODO add your handling code here:
        this.openNguoiHoc();
    }//GEN-LAST:event_mni_NguoihocActionPerformed

    private void lbl_NguoihocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_NguoihocMouseClicked
        // TODO add your handling code here:
        this.openNguoiHoc();
    }//GEN-LAST:event_lbl_NguoihocMouseClicked

    private void mni_HocvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_HocvienActionPerformed
        // TODO add your handling code here:
        this.openHocVien();
    }//GEN-LAST:event_mni_HocvienActionPerformed

    private void lbl_HocvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HocvienMouseClicked
        // TODO add your handling code here:
        this.openHocVien();
    }//GEN-LAST:event_lbl_HocvienMouseClicked

    private void mni_QuanLyNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_QuanLyNVActionPerformed
        // TODO add your handling code here:
        this.openNhanVien();
    }//GEN-LAST:event_mni_QuanLyNVActionPerformed

    private void mni_BangdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_BangdiemActionPerformed
        // TODO add your handling code here:
        this.openThongKe(0);
    }//GEN-LAST:event_mni_BangdiemActionPerformed

    private void mn_LuongNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_LuongNHActionPerformed
        // TODO add your handling code here:
        this.openThongKe(1);
    }//GEN-LAST:event_mn_LuongNHActionPerformed

    private void mni_DiemCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_DiemCDActionPerformed
        // TODO add your handling code here:
        this.openThongKe(2);
    }//GEN-LAST:event_mni_DiemCDActionPerformed

    private void mni_DoanhthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_DoanhthuActionPerformed
        // TODO add your handling code here:
        this.openThongKe(3);
    }//GEN-LAST:event_mni_DoanhthuActionPerformed

    private void mni_GioithieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_GioithieuActionPerformed
        // TODO add your handling code here:
        this.openGioiThieu();
    }//GEN-LAST:event_mni_GioithieuActionPerformed

    private void mni_HDSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_HDSDActionPerformed
        // TODO add your handling code here:
        this.openHuongDan();
    }//GEN-LAST:event_mni_HDSDActionPerformed

    private void lbl_HuongdanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HuongdanMouseClicked
        // TODO add your handling code here:
        this.openHuongDan();
    }//GEN-LAST:event_lbl_HuongdanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EduSys_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EduSys_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EduSys_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EduSys_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EduSys_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_Chuyende;
    private javax.swing.JLabel lbl_Dangxuat;
    private javax.swing.JLabel lbl_Dongho;
    private javax.swing.JLabel lbl_Hocvien;
    private javax.swing.JLabel lbl_Huongdan;
    private javax.swing.JLabel lbl_Images;
    private javax.swing.JLabel lbl_Ketthuc;
    private javax.swing.JLabel lbl_Khoahoc;
    private javax.swing.JLabel lbl_Nguoihoc;
    private javax.swing.JLabel lbl_TextQuanlyDT;
    private javax.swing.JMenuItem mn_LuongNH;
    private javax.swing.JMenuBar mnb;
    private javax.swing.JMenuItem mni_Bangdiem;
    private javax.swing.JMenuItem mni_Chuyende;
    private javax.swing.JMenuItem mni_Dangxuat;
    private javax.swing.JMenuItem mni_DiemCD;
    private javax.swing.JMenuItem mni_Doanhthu;
    private javax.swing.JMenuItem mni_DoiMK;
    private javax.swing.JMenuItem mni_Gioithieu;
    private javax.swing.JMenuItem mni_HDSD;
    private javax.swing.JMenuItem mni_Hocvien;
    private javax.swing.JMenuItem mni_Khoahoc;
    private javax.swing.JMenuItem mni_Nguoihoc;
    private javax.swing.JMenuItem mni_QuanLyNV;
    private javax.swing.JMenuItem mni_Thoat;
    private javax.swing.JMenu mnu_Hethong;
    private javax.swing.JMenu mnu_Quanly;
    private javax.swing.JMenu mnu_Thongke;
    private javax.swing.JMenu mnu_Trogiup;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl_Center;
    private javax.swing.JPanel pnl_Images;
    private javax.swing.JPanel pnl_Slide;
    private javax.swing.JPopupMenu.Separator spr;
    private javax.swing.JPopupMenu.Separator spr1;
    private javax.swing.JPopupMenu.Separator spr2;
    private javax.swing.JPopupMenu.Separator spr3;
    private javax.swing.JPopupMenu.Separator spr4;
    // End of variables declaration//GEN-END:variables

    private void init() {
        //chuyển frame ra giữa màn hình
        this.setLocationRelativeTo(null);
        //gọi hàm tạo icon tiêu đề
        this.setIconImage(XImage.getAppIcon());
        //mở các Dialog tương ứng khi chạy
        new ChaoMung_Dialog(this, true).setVisible(true);
        new DangNhap_Dialog(this, true).setVisible(true);
        if (!Auth.isLogin()) {
            System.exit(0);
        }
    }

    private void dongHo() {
        //lấy thời gian hệ thống đưa lên lbl_Dongho
        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat SDF = new SimpleDateFormat("HH:mm:ss a");
                String DH = SDF.format(now);
                lbl_Dongho.setText(DH);
            }
        }).start();
    }

    private void openDangXuat() {
        //mở Dialog DangNhap
        Auth.clear();
        new DangNhap_Dialog(this, true).setVisible(true);
    }

    private void openDoiMatKhau() {
        //mở Dialog đổi mật khẩu
        if (Auth.isLogin()) {
            new DoiMatKhau_Dialog(this, true).setVisible(true);
        } else {
            MsgBox.warning(this, "Vui Lòng Đăng Nhập Vào Hệ Thống !");
        }
    }

    private void ketThuc() {
        if (MsgBox.confirm(this, "Thoát EduSys ?")) {
            System.exit(0);
        }
    }

    private void openChuyenDe() {
        //mở Dialog chuyên đề     
        if (Auth.isLogin()) {
            new ChuyenDe_Dialog(this, true).setVisible(true);
        } else {
            MsgBox.warning(this, "Vui Lòng Đăng Nhập Vào Hệ Thống !");
        }
    }

    private void openKhoaHoc() {
        //mở Dialog khóa học
        if (Auth.isLogin()) {
            new KhoaHoc_Dialog(this, true).setVisible(true);
        } else {
            MsgBox.warning(this, "Vui Lòng Đăng Nhập Vào Hệ Thống !");
        }
    }

    private void openNguoiHoc() {
        //mở Dialog người học
        if (Auth.isLogin()) {
            new NguoiHoc_Dialog(this, true).setVisible(true);
        } else {
            MsgBox.warning(this, "Vui Lòng Đăng Nhập Vào Hệ Thống !");
        }
    }

    private void openHocVien() {
        //mở Dialog hoc viên
        if (Auth.isLogin()) {
            new HocVien_Dialog(this, true).setVisible(true);
        } else {
            MsgBox.warning(this, "Vui Lòng Đăng Nhập Vào Hệ Thống !");
        }
    }

    private void openNhanVien() {
        //mở Dialog nhân viên
        if (Auth.isLogin()) {
            new NhanVien_Dialog(this, true).setVisible(true);
        } else {
            MsgBox.warning(this, "Vui Lòng Đăng Nhập Vào Hệ Thống !");
        }
    }

    private void openThongKe(int index) {
        //mở Dialog thống kê
        if (Auth.isLogin()) {
            if (index == 3 && !Auth.isManager()) {
                MsgBox.warning(this, "Bạn Không Có Quyền Truy Cập Tab Doanh Thu !");
            } else {
                ThongKe_Dialog tk = new ThongKe_Dialog(this, true);
                tk.selectTab(index);
                tk.setVisible(true);

            }
        } else {
            MsgBox.warning(this, "Vui Lòng Đăng Nhập Vào Hệ Thống !");
        }
    }

    private void openGioiThieu() {
        //mở Dialog giới thiệu
        if (Auth.isLogin()) {
            new GioiThieu_Dialog(this, true).setVisible(true);
        } else {
            MsgBox.warning(this, "Vui Lòng Đăng Nhập Vào Hệ Thống !");
        }
    }

    private void openHuongDan() {
        try {
            Desktop.getDesktop().browse(new File("help/HDSD.pdf").toURI());
        } catch (IOException ex) {
            MsgBox.warning(this, "Không Tìm Thấy File Hướng Dẫn !");
        }
    }
}
