/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import DAO.ChuyenDeDAO;
import DAO.HocVienDAO;
import DAO.KhoaHocDAO;
import DAO.NguoiHocDAO;
import Entity.ChuyenDe;
import Entity.HocVien;
import Entity.KhoaHoc;
import Entity.NguoiHoc;
import Utils.Auth;
import Utils.MsgBox;
import Utils.XDate;
import Utils.XImage;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author vietm
 */
public class HocVien_Dialog extends java.awt.Dialog {

    /**
     * Creates new form HocVien_Dialog
     */
    public HocVien_Dialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        lbl_Quanly = new javax.swing.JLabel();
        pnl_Cbo = new javax.swing.JPanel();
        cbo_Chuyende = new javax.swing.JComboBox<>();
        cbo_Khoahoc = new javax.swing.JComboBox<>();
        lbl_Chuyende = new javax.swing.JLabel();
        lbl_Khoahoc = new javax.swing.JLabel();
        Tabs = new javax.swing.JTabbedPane();
        pnl_Hocvien = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Hocvien = new javax.swing.JTable();
        btn_XoaHV = new javax.swing.JButton();
        btn_Suadiem = new javax.swing.JButton();
        pnl_Nguoihoc = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Nguoihoc = new javax.swing.JTable();
        btn_ThemHV = new javax.swing.JButton();
        txt_Timkiem = new javax.swing.JTextField();
        spr1 = new javax.swing.JSeparator();
        lbl_Timkiem = new javax.swing.JLabel();
        spr2 = new javax.swing.JSeparator();

        setTitle("EduSys - QUẢN LÝ HỌC VIÊN");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        pnl1.setBackground(new java.awt.Color(255, 255, 255));

        lbl_Quanly.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Quanly.setForeground(new java.awt.Color(102, 102, 102));
        lbl_Quanly.setText("QUẢN LÝ HỌC VIÊN");

        pnl_Cbo.setBackground(new java.awt.Color(255, 255, 255));

        cbo_Chuyende.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbo_Chuyende.setForeground(new java.awt.Color(255, 102, 102));
        cbo_Chuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_ChuyendeActionPerformed(evt);
            }
        });

        cbo_Khoahoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbo_Khoahoc.setForeground(new java.awt.Color(255, 102, 102));
        cbo_Khoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_KhoahocActionPerformed(evt);
            }
        });

        lbl_Chuyende.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Chuyende.setForeground(new java.awt.Color(102, 102, 102));
        lbl_Chuyende.setText("CHUYÊN ĐỀ");

        lbl_Khoahoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Khoahoc.setForeground(new java.awt.Color(102, 102, 102));
        lbl_Khoahoc.setText("KHÓA HỌC");

        javax.swing.GroupLayout pnl_CboLayout = new javax.swing.GroupLayout(pnl_Cbo);
        pnl_Cbo.setLayout(pnl_CboLayout);
        pnl_CboLayout.setHorizontalGroup(
            pnl_CboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CboLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnl_CboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Chuyende)
                    .addComponent(cbo_Chuyende, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_CboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Khoahoc)
                    .addComponent(cbo_Khoahoc, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        pnl_CboLayout.setVerticalGroup(
            pnl_CboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CboLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnl_CboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Khoahoc)
                    .addComponent(lbl_Chuyende))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_CboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbo_Khoahoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_Chuyende, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        Tabs.setBackground(new java.awt.Color(255, 255, 255));
        Tabs.setForeground(new java.awt.Color(255, 102, 102));
        Tabs.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        pnl_Hocvien.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Hocvien.setForeground(new java.awt.Color(41, 168, 73));
        pnl_Hocvien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        tbl_Hocvien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_Hocvien.setForeground(new java.awt.Color(102, 102, 102));
        tbl_Hocvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TT", "MÃ HV", "MÃ NH", "HỌ TÊN", "ĐIỂM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Hocvien.setRowHeight(22);
        tbl_Hocvien.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(tbl_Hocvien);

        btn_XoaHV.setBackground(new java.awt.Color(102, 102, 102));
        btn_XoaHV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_XoaHV.setForeground(new java.awt.Color(255, 255, 255));
        btn_XoaHV.setText("Xóa Khỏi Khóa Học");
        btn_XoaHV.setBorder(null);
        btn_XoaHV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaHVActionPerformed(evt);
            }
        });

        btn_Suadiem.setBackground(new java.awt.Color(102, 102, 102));
        btn_Suadiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Suadiem.setForeground(new java.awt.Color(255, 255, 255));
        btn_Suadiem.setText("Cập Nhật Điểm");
        btn_Suadiem.setBorder(null);
        btn_Suadiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuadiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_HocvienLayout = new javax.swing.GroupLayout(pnl_Hocvien);
        pnl_Hocvien.setLayout(pnl_HocvienLayout);
        pnl_HocvienLayout.setHorizontalGroup(
            pnl_HocvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
            .addGroup(pnl_HocvienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_XoaHV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_Suadiem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_HocvienLayout.setVerticalGroup(
            pnl_HocvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_HocvienLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnl_HocvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_XoaHV, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Suadiem, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        Tabs.addTab("HỌC VIÊN", pnl_Hocvien);

        pnl_Nguoihoc.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Nguoihoc.setForeground(new java.awt.Color(41, 168, 73));
        pnl_Nguoihoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        tbl_Nguoihoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_Nguoihoc.setForeground(new java.awt.Color(102, 102, 102));
        tbl_Nguoihoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ NH", "HỌ TÊN", "GIỚI TÍNH", "NGÀY SINH", "ĐIỆN THOẠI", "EMAIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Nguoihoc.setRowHeight(22);
        tbl_Nguoihoc.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane2.setViewportView(tbl_Nguoihoc);

        btn_ThemHV.setBackground(new java.awt.Color(102, 102, 102));
        btn_ThemHV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ThemHV.setForeground(new java.awt.Color(255, 255, 255));
        btn_ThemHV.setText("Thêm Vào Khóa Học");
        btn_ThemHV.setBorder(null);
        btn_ThemHV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemHVActionPerformed(evt);
            }
        });

        txt_Timkiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_Timkiem.setForeground(new java.awt.Color(255, 102, 102));
        txt_Timkiem.setBorder(null);
        txt_Timkiem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_TimkiemCaretUpdate(evt);
            }
        });

        spr1.setBackground(new java.awt.Color(102, 102, 102));
        spr1.setForeground(new java.awt.Color(102, 102, 102));

        lbl_Timkiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Timkiem.setForeground(new java.awt.Color(102, 102, 102));
        lbl_Timkiem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Timkiem.setText("Tìm Kiếm");

        spr2.setBackground(new java.awt.Color(102, 102, 102));
        spr2.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout pnl_NguoihocLayout = new javax.swing.GroupLayout(pnl_Nguoihoc);
        pnl_Nguoihoc.setLayout(pnl_NguoihocLayout);
        pnl_NguoihocLayout.setHorizontalGroup(
            pnl_NguoihocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_NguoihocLayout.createSequentialGroup()
                .addGap(401, 411, Short.MAX_VALUE)
                .addComponent(btn_ThemHV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_NguoihocLayout.createSequentialGroup()
                .addComponent(lbl_Timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Timkiem))
            .addComponent(spr2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(spr1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnl_NguoihocLayout.setVerticalGroup(
            pnl_NguoihocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_NguoihocLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(spr2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_NguoihocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spr1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_ThemHV, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Tabs.addTab("NGƯỜI HỌC", pnl_Nguoihoc);

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabs)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Quanly)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnl_Cbo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Quanly)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Cbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tabs))
        );

        add(pnl1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btn_XoaHVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaHVActionPerformed
        // TODO add your handling code here:
        this.removeHocVien();
    }//GEN-LAST:event_btn_XoaHVActionPerformed

    private void btn_SuadiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuadiemActionPerformed
        // TODO add your handling code here:
        this.updateDiem();
    }//GEN-LAST:event_btn_SuadiemActionPerformed

    private void btn_ThemHVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemHVActionPerformed
        // TODO add your handling code here:
        this.addHocVien();
    }//GEN-LAST:event_btn_ThemHVActionPerformed

    private void cbo_ChuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_ChuyendeActionPerformed
        // TODO add your handling code here:
        this.fillComboBoxKhoaHoc();
    }//GEN-LAST:event_cbo_ChuyendeActionPerformed

    private void cbo_KhoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_KhoahocActionPerformed
        // TODO add your handling code here:
        this.fillTableHocVien();
    }//GEN-LAST:event_cbo_KhoahocActionPerformed

    private void txt_TimkiemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_TimkiemCaretUpdate
        // TODO add your handling code here:
        this.fillTableNguoiHoc();
    }//GEN-LAST:event_txt_TimkiemCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HocVien_Dialog dialog = new HocVien_Dialog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JButton btn_Suadiem;
    private javax.swing.JButton btn_ThemHV;
    private javax.swing.JButton btn_XoaHV;
    private javax.swing.JComboBox<String> cbo_Chuyende;
    private javax.swing.JComboBox<String> cbo_Khoahoc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_Chuyende;
    private javax.swing.JLabel lbl_Khoahoc;
    private javax.swing.JLabel lbl_Quanly;
    private javax.swing.JLabel lbl_Timkiem;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl_Cbo;
    private javax.swing.JPanel pnl_Hocvien;
    private javax.swing.JPanel pnl_Nguoihoc;
    private javax.swing.JSeparator spr1;
    private javax.swing.JSeparator spr2;
    private javax.swing.JTable tbl_Hocvien;
    private javax.swing.JTable tbl_Nguoihoc;
    private javax.swing.JTextField txt_Timkiem;
    // End of variables declaration//GEN-END:variables

    ChuyenDeDAO cddao = new ChuyenDeDAO();
    KhoaHocDAO khdao = new KhoaHocDAO();
    NguoiHocDAO nhdao = new NguoiHocDAO();
    HocVienDAO hvdao = new HocVienDAO();

    private void init() {
        //chuyển Dialog ra giữa
        this.setLocationRelativeTo(null);
        //gọi hàm set icon tiêu đề cho Dialog
        this.setIconImage(XImage.getAppIcon());
        this.fillComboBoxChuyenDe();
        DefaultTableCellRenderer render = new DefaultTableCellRenderer();
        render.setHorizontalAlignment(JLabel.CENTER);

        TableColumnModel model = tbl_Hocvien.getColumnModel();
        TableColumnModel modell = tbl_Nguoihoc.getColumnModel();
        model.getColumn(0).setMaxWidth(40);
        model.getColumn(1).setMaxWidth(50);
        model.getColumn(2).setMaxWidth(80);
        model.getColumn(4).setMaxWidth(50);
        
        modell.getColumn(0).setMaxWidth(65);
        modell.getColumn(2).setMaxWidth(65);
        modell.getColumn(3).setMaxWidth(90);
        modell.getColumn(4).setMaxWidth(90);
        
        model.getColumn(0).setCellRenderer(render);
        model.getColumn(1).setCellRenderer(render);
        model.getColumn(2).setCellRenderer(render);
        model.getColumn(4).setCellRenderer(render);
        
        modell.getColumn(0).setCellRenderer(render);
        modell.getColumn(1).setCellRenderer(render);
        modell.getColumn(2).setCellRenderer(render);
        modell.getColumn(4).setCellRenderer(render);
    }

    private void fillComboBoxChuyenDe() {
        DefaultComboBoxModel dcm = (DefaultComboBoxModel) cbo_Chuyende.getModel();
        dcm.removeAllElements();
        List<ChuyenDe> list = cddao.selectAll();
        for (ChuyenDe cd : list) {
            dcm.addElement(cd);
        }
        this.fillComboBoxKhoaHoc();
    }

    private void fillComboBoxKhoaHoc() {
        DefaultComboBoxModel dcm = (DefaultComboBoxModel) cbo_Khoahoc.getModel();
        dcm.removeAllElements();
        ChuyenDe chuyenDe = (ChuyenDe) cbo_Chuyende.getSelectedItem();
        if (chuyenDe != null) {
            List<KhoaHoc> list = khdao.selectByChuyenDe(chuyenDe.getMaCD());
            for (KhoaHoc kh : list) {
                dcm.addElement(kh);
            }
            this.fillTableHocVien();
        }
    }

    private void fillTableHocVien() {
        DefaultTableModel dtm = (DefaultTableModel) tbl_Hocvien.getModel();
        dtm.setRowCount(0);
        KhoaHoc khoaHoc = (KhoaHoc) cbo_Khoahoc.getSelectedItem();
        if (khoaHoc != null) {
            List<HocVien> list = hvdao.selectByKhoaHoc(khoaHoc.getMaKH());
            //duyệt từng hv trong list
            for (int i = 0; i < list.size(); i++) {
                HocVien hv = list.get(i);
                String hoTen = nhdao.selectById(hv.getMaNH()).getHoTen();
                dtm.addRow(new Object[]{i + 1, hv.getMaHV(), hv.getMaNH(), hoTen, hv.getDiem()});
            }
            this.fillTableNguoiHoc();
        }
    }

    private void fillTableNguoiHoc() {
        DefaultTableModel dtm = (DefaultTableModel) tbl_Nguoihoc.getModel();
        dtm.setRowCount(0);
        KhoaHoc khoaHoc = (KhoaHoc) cbo_Khoahoc.getSelectedItem();
        String key = txt_Timkiem.getText();
        List<NguoiHoc> list = nhdao.selectNotInCourse(khoaHoc.getMaKH(), key);
        for (NguoiHoc nh : list) {
            dtm.addRow(new Object[]{nh.getMaNH(), nh.getHoTen(), nh.isGioiTinh() ? "Nam" : "Nữ",
                XDate.toString(nh.getNgaySinh(), "dd/MM/yyyy"), nh.getDienThoai(), nh.getEmail()});
        }
    }

    private void removeHocVien() {
        if (!Auth.isManager()) {
            MsgBox.warning(this, "Bạn Không Có Quyền Xóa Học Viên !");
        } else {
            if (MsgBox.confirm(this, "Xóa Học Viên ?")) {
                for (int row : tbl_Hocvien.getSelectedRows()) {
                    int maHV = (Integer) tbl_Hocvien.getValueAt(row, 1);
                    hvdao.delete(maHV);
                }
                this.fillTableHocVien();
                MsgBox.alert(this, "Đã Xóa");
            }
        }
    }

    private void addHocVien() {
        KhoaHoc khoaHoc = (KhoaHoc) cbo_Khoahoc.getSelectedItem();
        //quét từng người học đã chọn tạo thành từng học viên add vào CSDL
        for (int row : tbl_Nguoihoc.getSelectedRows()) {
            String maNH = (String) tbl_Nguoihoc.getValueAt(row, 0);
            HocVien hv = new HocVien();
            hv.setMaKH(khoaHoc.getMaKH());
            hv.setDiem(0);
            hv.setMaNH(maNH);
            hvdao.insert(hv);
        }
        this.fillTableHocVien();
        MsgBox.alert(this, "Thêm Thành Công");
        this.Tabs.setSelectedIndex(0);
    }

    private void updateDiem() {
        for (int i = 0; i < tbl_Hocvien.getRowCount(); i++) {
            int maHV = (Integer) tbl_Hocvien.getValueAt(i, 1);
            HocVien hv = hvdao.selectById(maHV);
            String diem = String.valueOf(tbl_Hocvien.getValueAt(i, 4));
            hv.setDiem(Double.parseDouble(diem));
            hvdao.update(hv);
        }
        MsgBox.alert(this, "Cập Nhật Điểm Thành Công !");
    }
}
