/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import DAO.ChuyenDeDAO;
import DAO.KhoaHocDAO;
import Entity.ChuyenDe;
import Entity.KhoaHoc;
import Utils.Auth;
import Utils.MsgBox;
import Utils.XDate;
import Utils.XImage;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vietm
 */
public class KhoaHoc_Dialog extends java.awt.Dialog {

    /**
     * Creates new form Khoahoc_Dialog
     */
    public KhoaHoc_Dialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        pnl_Chuyende = new javax.swing.JPanel();
        cbo_Chuyende = new javax.swing.JComboBox<>();
        lbl_CDCboBox = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        pnl_Capnhat = new javax.swing.JPanel();
        lbl_TextCD = new javax.swing.JLabel();
        lbl_Khaigiang = new javax.swing.JLabel();
        txt_Khaigiang = new javax.swing.JTextField();
        spr1 = new javax.swing.JSeparator();
        spr2 = new javax.swing.JSeparator();
        lbl_Hocphi = new javax.swing.JLabel();
        lbl_Thoiluong = new javax.swing.JLabel();
        spr3 = new javax.swing.JSeparator();
        txt_hocphi = new javax.swing.JTextField();
        spr4 = new javax.swing.JSeparator();
        txt_thoiluong = new javax.swing.JTextField();
        lbl_Nguoitao = new javax.swing.JLabel();
        lbl_Ngaytao = new javax.swing.JLabel();
        spr5 = new javax.swing.JSeparator();
        txt_NguoiTao = new javax.swing.JTextField();
        spr6 = new javax.swing.JSeparator();
        txt_Ngaytao = new javax.swing.JTextField();
        lbl_ghichu = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Ghichu = new javax.swing.JTextArea();
        btn_Them = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Moi = new javax.swing.JButton();
        btn_First = new javax.swing.JButton();
        btn_Prev = new javax.swing.JButton();
        btn_Next = new javax.swing.JButton();
        btn_Last = new javax.swing.JButton();
        txt_TenCD = new javax.swing.JTextField();
        pnl_Danhsach = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Khoahoc = new javax.swing.JTable();
        lbl_QuanLY = new javax.swing.JLabel();

        setTitle("EduSys - QUẢN LÝ KHÓA HỌC");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        pnl1.setBackground(new java.awt.Color(255, 255, 255));

        pnl_Chuyende.setBackground(new java.awt.Color(255, 255, 255));

        cbo_Chuyende.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbo_Chuyende.setForeground(new java.awt.Color(255, 102, 102));
        cbo_Chuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_ChuyendeActionPerformed(evt);
            }
        });

        lbl_CDCboBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_CDCboBox.setForeground(new java.awt.Color(102, 102, 102));
        lbl_CDCboBox.setText("CHUYÊN ĐỀ");

        javax.swing.GroupLayout pnl_ChuyendeLayout = new javax.swing.GroupLayout(pnl_Chuyende);
        pnl_Chuyende.setLayout(pnl_ChuyendeLayout);
        pnl_ChuyendeLayout.setHorizontalGroup(
            pnl_ChuyendeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ChuyendeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnl_ChuyendeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_CDCboBox)
                    .addComponent(cbo_Chuyende, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_ChuyendeLayout.setVerticalGroup(
            pnl_ChuyendeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ChuyendeLayout.createSequentialGroup()
                .addComponent(lbl_CDCboBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbo_Chuyende, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        tabs.setBackground(new java.awt.Color(255, 255, 255));
        tabs.setForeground(new java.awt.Color(255, 102, 102));
        tabs.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        pnl_Capnhat.setBackground(new java.awt.Color(255, 255, 255));

        lbl_TextCD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_TextCD.setForeground(new java.awt.Color(102, 102, 102));
        lbl_TextCD.setText("Chuyên Đề");

        lbl_Khaigiang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Khaigiang.setForeground(new java.awt.Color(102, 102, 102));
        lbl_Khaigiang.setText("Khai Giảng (dd/MM/yyyy)");

        txt_Khaigiang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_Khaigiang.setForeground(new java.awt.Color(255, 102, 102));
        txt_Khaigiang.setBorder(null);

        spr1.setBackground(new java.awt.Color(102, 102, 102));
        spr1.setForeground(new java.awt.Color(102, 102, 102));

        spr2.setBackground(new java.awt.Color(102, 102, 102));
        spr2.setForeground(new java.awt.Color(102, 102, 102));

        lbl_Hocphi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Hocphi.setForeground(new java.awt.Color(102, 102, 102));
        lbl_Hocphi.setText("Học Phí");

        lbl_Thoiluong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Thoiluong.setForeground(new java.awt.Color(102, 102, 102));
        lbl_Thoiluong.setText("Thời Lượng (Giờ)");

        spr3.setBackground(new java.awt.Color(102, 102, 102));
        spr3.setForeground(new java.awt.Color(102, 102, 102));

        txt_hocphi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_hocphi.setForeground(new java.awt.Color(255, 102, 102));
        txt_hocphi.setBorder(null);

        spr4.setBackground(new java.awt.Color(102, 102, 102));
        spr4.setForeground(new java.awt.Color(102, 102, 102));

        txt_thoiluong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_thoiluong.setForeground(new java.awt.Color(255, 102, 102));
        txt_thoiluong.setBorder(null);

        lbl_Nguoitao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Nguoitao.setForeground(new java.awt.Color(102, 102, 102));
        lbl_Nguoitao.setText("Người Tạo");

        lbl_Ngaytao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Ngaytao.setForeground(new java.awt.Color(102, 102, 102));
        lbl_Ngaytao.setText("Ngày Tạo (dd/MM/yyyy)");

        spr5.setBackground(new java.awt.Color(102, 102, 102));
        spr5.setForeground(new java.awt.Color(102, 102, 102));

        txt_NguoiTao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_NguoiTao.setForeground(new java.awt.Color(255, 102, 102));
        txt_NguoiTao.setBorder(null);

        spr6.setBackground(new java.awt.Color(102, 102, 102));
        spr6.setForeground(new java.awt.Color(102, 102, 102));

        txt_Ngaytao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_Ngaytao.setForeground(new java.awt.Color(255, 102, 102));
        txt_Ngaytao.setBorder(null);

        lbl_ghichu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_ghichu.setForeground(new java.awt.Color(102, 102, 102));
        lbl_ghichu.setText("Ghi Chú");

        txt_Ghichu.setColumns(20);
        txt_Ghichu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_Ghichu.setForeground(new java.awt.Color(255, 102, 102));
        txt_Ghichu.setRows(5);
        jScrollPane2.setViewportView(txt_Ghichu);

        btn_Them.setBackground(new java.awt.Color(102, 102, 102));
        btn_Them.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Them.setForeground(new java.awt.Color(255, 255, 255));
        btn_Them.setText("Thêm");
        btn_Them.setBorder(null);
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Sua.setBackground(new java.awt.Color(102, 102, 102));
        btn_Sua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_Sua.setText("Sửa");
        btn_Sua.setBorder(null);
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Xoa.setBackground(new java.awt.Color(102, 102, 102));
        btn_Xoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_Xoa.setText("Xóa");
        btn_Xoa.setBorder(null);
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_Moi.setBackground(new java.awt.Color(102, 102, 102));
        btn_Moi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Moi.setForeground(new java.awt.Color(255, 255, 255));
        btn_Moi.setText("Mới");
        btn_Moi.setBorder(null);
        btn_Moi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MoiActionPerformed(evt);
            }
        });

        btn_First.setBackground(new java.awt.Color(102, 102, 102));
        btn_First.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_First.setForeground(new java.awt.Color(255, 255, 255));
        btn_First.setText("|<");
        btn_First.setBorder(null);
        btn_First.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FirstActionPerformed(evt);
            }
        });

        btn_Prev.setBackground(new java.awt.Color(102, 102, 102));
        btn_Prev.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Prev.setForeground(new java.awt.Color(255, 255, 255));
        btn_Prev.setText("<<");
        btn_Prev.setBorder(null);
        btn_Prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrevActionPerformed(evt);
            }
        });

        btn_Next.setBackground(new java.awt.Color(102, 102, 102));
        btn_Next.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Next.setForeground(new java.awt.Color(255, 255, 255));
        btn_Next.setText(">>");
        btn_Next.setBorder(null);
        btn_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NextActionPerformed(evt);
            }
        });

        btn_Last.setBackground(new java.awt.Color(102, 102, 102));
        btn_Last.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Last.setForeground(new java.awt.Color(255, 255, 255));
        btn_Last.setText(">|");
        btn_Last.setBorder(null);
        btn_Last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LastActionPerformed(evt);
            }
        });

        txt_TenCD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_TenCD.setForeground(new java.awt.Color(255, 102, 102));
        txt_TenCD.setBorder(null);

        javax.swing.GroupLayout pnl_CapnhatLayout = new javax.swing.GroupLayout(pnl_Capnhat);
        pnl_Capnhat.setLayout(pnl_CapnhatLayout);
        pnl_CapnhatLayout.setHorizontalGroup(
            pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                        .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                                .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_TextCD)
                                    .addComponent(spr2, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                                    .addComponent(lbl_Hocphi)
                                    .addComponent(txt_TenCD))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_Thoiluong)
                                    .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_Khaigiang, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                                        .addComponent(lbl_Khaigiang)
                                        .addComponent(spr1))))
                            .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                                .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_hocphi)
                                    .addComponent(spr3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_thoiluong)
                                    .addComponent(spr4, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                        .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_NguoiTao)
                            .addComponent(spr5, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Ngaytao)
                            .addComponent(spr6, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                        .addComponent(lbl_ghichu)
                        .addContainerGap(541, Short.MAX_VALUE))
                    .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                        .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Moi, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_First, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Prev, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Last, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                        .addComponent(lbl_Nguoitao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_Ngaytao)
                        .addGap(114, 114, 114))))
        );
        pnl_CapnhatLayout.setVerticalGroup(
            pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TextCD)
                    .addComponent(lbl_Khaigiang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Khaigiang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TenCD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spr1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spr2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Hocphi)
                    .addComponent(lbl_Thoiluong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                        .addComponent(txt_hocphi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spr3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                        .addComponent(txt_thoiluong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spr4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Nguoitao)
                    .addComponent(lbl_Ngaytao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                        .addComponent(txt_NguoiTao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spr5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                        .addComponent(txt_Ngaytao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spr6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_ghichu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Moi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_First, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Prev, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Last, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tabs.addTab("Cập Nhật", pnl_Capnhat);

        pnl_Danhsach.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Danhsach.setLayout(new java.awt.BorderLayout());

        tbl_Khoahoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_Khoahoc.setForeground(new java.awt.Color(102, 102, 102));
        tbl_Khoahoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MÃ KH", "THỜI LƯỢNG", "HỌC PHÍ", "KHAI GIẢNG", "NGƯỜI TẠO", "NGÀY TẠO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Khoahoc.setRowHeight(22);
        tbl_Khoahoc.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_Khoahoc.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_Khoahoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_KhoahocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Khoahoc);

        pnl_Danhsach.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        tabs.addTab("Danh Sách", pnl_Danhsach);

        lbl_QuanLY.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_QuanLY.setForeground(new java.awt.Color(102, 102, 102));
        lbl_QuanLY.setText("QUẢN LÝ KHÓA HỌC");

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_QuanLY)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnl_Chuyende, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_QuanLY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Chuyende, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
        );

        add(pnl1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void cbo_ChuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_ChuyendeActionPerformed
        // TODO add your handling code here:
        this.chonChuyenDe();
    }//GEN-LAST:event_cbo_ChuyendeActionPerformed

    private void tbl_KhoahocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KhoahocMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            this.row = tbl_Khoahoc.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tbl_KhoahocMouseClicked

    private void btn_MoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MoiActionPerformed
        // TODO add your handling code here:
        this.clearForm();
    }//GEN-LAST:event_btn_MoiActionPerformed

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        this.insert();
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_FirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FirstActionPerformed
        // TODO add your handling code here:
        this.first();
    }//GEN-LAST:event_btn_FirstActionPerformed

    private void btn_PrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrevActionPerformed
        // TODO add your handling code here:
        this.prev();
    }//GEN-LAST:event_btn_PrevActionPerformed

    private void btn_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NextActionPerformed
        // TODO add your handling code here:
        this.next();
    }//GEN-LAST:event_btn_NextActionPerformed

    private void btn_LastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LastActionPerformed
        // TODO add your handling code here:
        this.last();
    }//GEN-LAST:event_btn_LastActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KhoaHoc_Dialog dialog = new KhoaHoc_Dialog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_First;
    private javax.swing.JButton btn_Last;
    private javax.swing.JButton btn_Moi;
    private javax.swing.JButton btn_Next;
    private javax.swing.JButton btn_Prev;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JComboBox<String> cbo_Chuyende;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_CDCboBox;
    private javax.swing.JLabel lbl_Hocphi;
    private javax.swing.JLabel lbl_Khaigiang;
    private javax.swing.JLabel lbl_Ngaytao;
    private javax.swing.JLabel lbl_Nguoitao;
    private javax.swing.JLabel lbl_QuanLY;
    private javax.swing.JLabel lbl_TextCD;
    private javax.swing.JLabel lbl_Thoiluong;
    private javax.swing.JLabel lbl_ghichu;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl_Capnhat;
    private javax.swing.JPanel pnl_Chuyende;
    private javax.swing.JPanel pnl_Danhsach;
    private javax.swing.JSeparator spr1;
    private javax.swing.JSeparator spr2;
    private javax.swing.JSeparator spr3;
    private javax.swing.JSeparator spr4;
    private javax.swing.JSeparator spr5;
    private javax.swing.JSeparator spr6;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tbl_Khoahoc;
    private javax.swing.JTextArea txt_Ghichu;
    private javax.swing.JTextField txt_Khaigiang;
    private javax.swing.JTextField txt_Ngaytao;
    private javax.swing.JTextField txt_NguoiTao;
    private javax.swing.JTextField txt_TenCD;
    private javax.swing.JTextField txt_hocphi;
    private javax.swing.JTextField txt_thoiluong;
    // End of variables declaration//GEN-END:variables

    KhoaHocDAO khdao = new KhoaHocDAO();
    ChuyenDeDAO cddao = new ChuyenDeDAO();
    int row = -1;

    private void init() {
        //chuyển Dialog ra giữa
        this.setLocationRelativeTo(null);
        //gọi hàm tạo icon tiêu đề cho Dialog
        this.setIconImage(XImage.getAppIcon());
        txt_TenCD.setEditable(false);
        txt_Khaigiang.setText("00/00/0000");
        this.fillComboBoxChuyenDe();
        this.fillTable();
        this.row = -1;
        this.updateStatus();
    }

    private void fillTable() {
        DefaultTableModel dtm = (DefaultTableModel) tbl_Khoahoc.getModel();
        dtm.setRowCount(0);
        try {
            ChuyenDe chuyenDe = (ChuyenDe) cbo_Chuyende.getSelectedItem();
            List<KhoaHoc> list = khdao.selectByChuyenDe(chuyenDe.getMaCD());
            for (KhoaHoc kh : list) {
                Object[] row = {kh.getMaKH(), kh.getThoiLuong(), kh.getHocPhi(), XDate.toString(kh.getNgayKG(), "dd/MM/yyyy"), kh.getMaNV(), XDate.toString(kh.getNgayTao(), "dd/MM/yyyy")};
                dtm.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.warning(this, "Lỗi Truy Vấn Dữ Liệu !");
        }
    }

    private void setForm(KhoaHoc kh) {
        ChuyenDe cd = (ChuyenDe) cbo_Chuyende.getSelectedItem();
        txt_TenCD.setText(cd.getTenCD());
        txt_Khaigiang.setText(XDate.toString(kh.getNgayKG(), "dd/MM/yyyy"));
        txt_hocphi.setText(String.valueOf(kh.getHocPhi()));
        txt_thoiluong.setText(String.valueOf(kh.getThoiLuong()));
        txt_NguoiTao.setText(kh.getMaNV());
        txt_Ngaytao.setText(XDate.toString(kh.getNgayTao(), "dd/MM/yyyy"));
        txt_Ghichu.setText(kh.getGhiChu());
    }

    private void settxt(KhoaHoc kh) {
        txt_Ngaytao.setText(XDate.toString(kh.getNgayTao(), "dd/MM/yyyy"));
        txt_NguoiTao.setText(Auth.user.getMaNV());
    }

    KhoaHoc getForm() {
        KhoaHoc kh = new KhoaHoc();
        ChuyenDe cd = (ChuyenDe) cbo_Chuyende.getSelectedItem();
        kh.setMaCD(cd.getMaCD());
        kh.setHocPhi(Double.valueOf(txt_hocphi.getText()));
        kh.setThoiLuong(Integer.valueOf(txt_thoiluong.getText()));
        kh.setNgayKG(XDate.toDate(txt_Khaigiang.getText(), "dd/MM/yyyy"));
        kh.setGhiChu(txt_Ghichu.getText());
        kh.setMaNV(Auth.user.getMaNV());
        kh.setNgayTao(kh.getNgayTao());
        return kh;
    }

    private void clearForm() {
        KhoaHoc kh = new KhoaHoc();
        txt_Khaigiang.setText("00/00/0000");
        txt_Ghichu.setText("");
        this.settxt(kh);
        tabs.setSelectedIndex(1);
        this.row = -1;
        this.updateStatus();
    }

    private void insert() {
        KhoaHoc kh = getForm();
        String ngKG = txt_Khaigiang.getText();
        String ghiChu = txt_Ghichu.getText();
        if (!Auth.isManager()) {
            MsgBox.warning(this, "Bạn Không Thể Thêm Khóa Học !");
        } else if (ngKG.equals("") || ghiChu.equals("")) {
            MsgBox.warning(this, "Vui Lòng Nhập Đầy Đủ Thông Tin Khóa Học !");
        } else {
            try {
                khdao.insert(kh);
                this.fillTable();
                MsgBox.alert(this, "Thêm Thành Công");
                this.clearForm();
            } catch (Exception e) {
                MsgBox.warning(this, "Thêm Thất Bại !");
            }
        }
    }

    private void update() {
        KhoaHoc kh = getForm();
        int maKH = (int) tbl_Khoahoc.getValueAt(this.row, 0);
        kh.setMaKH(maKH);
        try {
            khdao.update(kh);
            this.fillTable();
            MsgBox.alert(this, "Cập Nhật Thành Công");
        } catch (Exception e) {
            MsgBox.warning(this, "Cập Nhật Thất Bại !");
        }
    }

    private void delete() {
        int maKH = (int) tbl_Khoahoc.getValueAt(this.row, 0);
        if (!Auth.isManager()) {
            MsgBox.warning(this, "Bạn Không Có Quyền Xóa Khóa Học !");
        } else if (MsgBox.confirm(this, "Xóa Khóa Học ?")) {
            try {
                khdao.delete(maKH);
                this.fillTable();
                MsgBox.alert(this, "Xóa Thành Công");
                this.clearForm();
            } catch (Exception e) {
                MsgBox.alert(this, "Xóa Thất Bại !");
            }
        }
    }

    private void edit() {
        int maKH = (int) tbl_Khoahoc.getValueAt(this.row, 0);
        KhoaHoc kh = khdao.selectById(maKH);
        this.setForm(kh);
        tabs.setSelectedIndex(0);
        this.updateStatus();
    }

    private void first() {
        this.row = 0;
        this.edit();
    }

    private void prev() {
        if (this.row > 0) {
            this.row--;
            this.edit();
        }
    }

    private void next() {
        if (this.row < tbl_Khoahoc.getRowCount() - 1) {
            this.row++;
            this.edit();
        }
    }

    private void last() {
        this.row = tbl_Khoahoc.getRowCount() - 1;
        this.edit();
    }

    private void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tbl_Khoahoc.getRowCount() - 1);
        //trạng thai form
        txt_hocphi.setEditable(!edit);
        txt_thoiluong.setEditable(!edit);
        txt_NguoiTao.setEditable(!edit);
        txt_Ngaytao.setEditable(!edit);
        btn_Them.setEnabled(!edit);
        btn_Sua.setEnabled(edit);
        btn_Xoa.setEnabled(edit);
        //trạng thái diều hướng
        btn_First.setEnabled(edit && !first);
        btn_Prev.setEnabled(edit && !first);
        btn_Next.setEnabled(edit && !last);
        btn_Last.setEnabled(edit && !last);
        //trạng thái text
        txt_hocphi.setEditable(false);
        txt_thoiluong.setEditable(false);
        txt_NguoiTao.setEditable(false);
        txt_Ngaytao.setEditable(false);
    }

    private void fillComboBoxChuyenDe() {
        DefaultComboBoxModel dcm = (DefaultComboBoxModel) cbo_Chuyende.getModel();
        dcm.removeAllElements();
        List<ChuyenDe> list = cddao.selectAll();
        for (ChuyenDe cd : list) {
            dcm.addElement(cd);
        }
    }

    private void chonChuyenDe() {
        KhoaHoc kh = new KhoaHoc();
        ChuyenDe chuyenDe = (ChuyenDe) cbo_Chuyende.getSelectedItem();
        txt_thoiluong.setText(String.valueOf(chuyenDe.getThoiLuong()));
        txt_hocphi.setText(String.valueOf(chuyenDe.getHocPhi()));
        txt_TenCD.setText(chuyenDe.getTenCD());
        txt_Ghichu.setText(chuyenDe.getTenCD());
        this.settxt(kh);
        this.fillTable();
        this.row = -1;
        this.updateStatus();
        tabs.setSelectedIndex(1);
    }
}
