/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import DAO.NguoiHocDAO;
import Entity.NguoiHoc;
import Utils.Auth;
import Utils.MsgBox;
import Utils.XDate;
import Utils.XImage;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vietm
 */
public class NguoiHoc_Dialog extends java.awt.Dialog {

    /**
     * Creates new form NguoiHoc_Dialog
     */
    public NguoiHoc_Dialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnl1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        pnl_CapNhat = new javax.swing.JPanel();
        lbl_MaNH = new javax.swing.JLabel();
        spr2 = new javax.swing.JSeparator();
        lbl_HoTen = new javax.swing.JLabel();
        spr3 = new javax.swing.JSeparator();
        txt_Ngaysinh = new javax.swing.JTextField();
        spr4 = new javax.swing.JSeparator();
        lbl_Ngaysinh = new javax.swing.JLabel();
        lbl_gioitinh = new javax.swing.JLabel();
        rdo_Nam = new javax.swing.JRadioButton();
        rdo_Nu = new javax.swing.JRadioButton();
        lbl_Dienthoai = new javax.swing.JLabel();
        txt_Dienthoai = new javax.swing.JTextField();
        spr5 = new javax.swing.JSeparator();
        lbl_Email = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        spr6 = new javax.swing.JSeparator();
        lbl_ghichu = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Ghichu = new javax.swing.JTextArea();
        txt_Hoten = new javax.swing.JTextField();
        txt_MaNH = new javax.swing.JTextField();
        btn_Them = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Moi = new javax.swing.JButton();
        btn_First = new javax.swing.JButton();
        btn_Prev = new javax.swing.JButton();
        btn_Next = new javax.swing.JButton();
        btn_Last = new javax.swing.JButton();
        pnl_Danhsach = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Nguoihoc = new javax.swing.JTable();
        txt_Timkiem = new javax.swing.JTextField();
        lbl_Search = new javax.swing.JLabel();

        setTitle("EduSys - QUẢN LÝ NGƯỜI HỌC");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        pnl1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("QUẢN LÝ NGƯỜI HỌC");

        tabs.setForeground(new java.awt.Color(255, 102, 102));
        tabs.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        pnl_CapNhat.setBackground(new java.awt.Color(255, 255, 255));

        lbl_MaNH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_MaNH.setForeground(new java.awt.Color(102, 102, 102));
        lbl_MaNH.setText("Mã Người Học");

        spr2.setBackground(new java.awt.Color(102, 102, 102));
        spr2.setForeground(new java.awt.Color(102, 102, 102));

        lbl_HoTen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_HoTen.setForeground(new java.awt.Color(102, 102, 102));
        lbl_HoTen.setText("Họ Và Tên");

        spr3.setBackground(new java.awt.Color(102, 102, 102));
        spr3.setForeground(new java.awt.Color(102, 102, 102));

        txt_Ngaysinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_Ngaysinh.setForeground(new java.awt.Color(255, 102, 102));
        txt_Ngaysinh.setBorder(null);

        spr4.setBackground(new java.awt.Color(102, 102, 102));
        spr4.setForeground(new java.awt.Color(102, 102, 102));

        lbl_Ngaysinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Ngaysinh.setForeground(new java.awt.Color(102, 102, 102));
        lbl_Ngaysinh.setText("Ngày Sinh (dd/MM/yyyy)");

        lbl_gioitinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_gioitinh.setForeground(new java.awt.Color(102, 102, 102));
        lbl_gioitinh.setText("Giới Tính");

        rdo_Nam.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdo_Nam);
        rdo_Nam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdo_Nam.setForeground(new java.awt.Color(102, 102, 102));
        rdo_Nam.setText("Nam");

        rdo_Nu.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdo_Nu);
        rdo_Nu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdo_Nu.setForeground(new java.awt.Color(102, 102, 102));
        rdo_Nu.setText("Nữ");

        lbl_Dienthoai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Dienthoai.setForeground(new java.awt.Color(102, 102, 102));
        lbl_Dienthoai.setText("Điện Thoại");

        txt_Dienthoai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_Dienthoai.setForeground(new java.awt.Color(255, 102, 102));
        txt_Dienthoai.setBorder(null);

        spr5.setBackground(new java.awt.Color(102, 102, 102));
        spr5.setForeground(new java.awt.Color(102, 102, 102));

        lbl_Email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Email.setForeground(new java.awt.Color(102, 102, 102));
        lbl_Email.setText("Email");

        txt_Email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_Email.setForeground(new java.awt.Color(255, 102, 102));
        txt_Email.setBorder(null);

        spr6.setBackground(new java.awt.Color(102, 102, 102));
        spr6.setForeground(new java.awt.Color(102, 102, 102));

        lbl_ghichu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_ghichu.setForeground(new java.awt.Color(102, 102, 102));
        lbl_ghichu.setText("Ghi Chú");

        txt_Ghichu.setColumns(20);
        txt_Ghichu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_Ghichu.setForeground(new java.awt.Color(255, 102, 102));
        txt_Ghichu.setRows(5);
        jScrollPane2.setViewportView(txt_Ghichu);

        txt_Hoten.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_Hoten.setForeground(new java.awt.Color(255, 102, 102));
        txt_Hoten.setBorder(null);

        txt_MaNH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_MaNH.setForeground(new java.awt.Color(255, 102, 102));
        txt_MaNH.setBorder(null);

        btn_Them.setBackground(new java.awt.Color(102, 102, 102));
        btn_Them.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Them.setForeground(new java.awt.Color(255, 255, 255));
        btn_Them.setText("Thêm");
        btn_Them.setBorder(null);
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Sua.setBackground(new java.awt.Color(102, 102, 102));
        btn_Sua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_Sua.setText("Sửa");
        btn_Sua.setBorder(null);
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Xoa.setBackground(new java.awt.Color(102, 102, 102));
        btn_Xoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_Xoa.setText("Xóa");
        btn_Xoa.setBorder(null);
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_Moi.setBackground(new java.awt.Color(102, 102, 102));
        btn_Moi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Moi.setForeground(new java.awt.Color(255, 255, 255));
        btn_Moi.setText("Mới");
        btn_Moi.setBorder(null);
        btn_Moi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MoiActionPerformed(evt);
            }
        });

        btn_First.setBackground(new java.awt.Color(102, 102, 102));
        btn_First.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_First.setForeground(new java.awt.Color(255, 255, 255));
        btn_First.setText("|<");
        btn_First.setBorder(null);
        btn_First.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FirstActionPerformed(evt);
            }
        });

        btn_Prev.setBackground(new java.awt.Color(102, 102, 102));
        btn_Prev.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Prev.setForeground(new java.awt.Color(255, 255, 255));
        btn_Prev.setText("<<");
        btn_Prev.setBorder(null);
        btn_Prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrevActionPerformed(evt);
            }
        });

        btn_Next.setBackground(new java.awt.Color(102, 102, 102));
        btn_Next.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Next.setForeground(new java.awt.Color(255, 255, 255));
        btn_Next.setText(">>");
        btn_Next.setBorder(null);
        btn_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NextActionPerformed(evt);
            }
        });

        btn_Last.setBackground(new java.awt.Color(102, 102, 102));
        btn_Last.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Last.setForeground(new java.awt.Color(255, 255, 255));
        btn_Last.setText(">|");
        btn_Last.setBorder(null);
        btn_Last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_CapNhatLayout = new javax.swing.GroupLayout(pnl_CapNhat);
        pnl_CapNhat.setLayout(pnl_CapNhatLayout);
        pnl_CapNhatLayout.setHorizontalGroup(
            pnl_CapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CapNhatLayout.createSequentialGroup()
                .addGroup(pnl_CapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_CapNhatLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_MaNH))
                    .addGroup(pnl_CapNhatLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(spr2, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_CapNhatLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_HoTen))
                    .addGroup(pnl_CapNhatLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(spr3, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_CapNhatLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_gioitinh)
                        .addGap(252, 252, 252)
                        .addComponent(lbl_Ngaysinh))
                    .addGroup(pnl_CapNhatLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(rdo_Nam)
                        .addGap(30, 30, 30)
                        .addComponent(rdo_Nu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159)
                        .addComponent(txt_Ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_CapNhatLayout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(spr4, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_CapNhatLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_Dienthoai)
                        .addGap(240, 240, 240)
                        .addComponent(lbl_Email))
                    .addGroup(pnl_CapNhatLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txt_Dienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_CapNhatLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(spr5, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(spr6, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_CapNhatLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_ghichu))
                    .addGroup(pnl_CapNhatLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_CapNhatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_CapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Hoten, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_MaNH)
                    .addGroup(pnl_CapNhatLayout.createSequentialGroup()
                        .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Moi, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_First, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Prev, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Last, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnl_CapNhatLayout.setVerticalGroup(
            pnl_CapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CapNhatLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lbl_MaNH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_MaNH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spr2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lbl_HoTen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spr3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(pnl_CapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_gioitinh)
                    .addComponent(lbl_Ngaysinh))
                .addGap(6, 6, 6)
                .addGroup(pnl_CapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_CapNhatLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(pnl_CapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdo_Nam)
                            .addComponent(rdo_Nu))))
                .addGap(6, 6, 6)
                .addComponent(spr4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(pnl_CapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Dienthoai)
                    .addComponent(lbl_Email))
                .addGap(6, 6, 6)
                .addGroup(pnl_CapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Dienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnl_CapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spr5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spr6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(lbl_ghichu)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_CapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Moi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_First, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Prev, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Last, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabs.addTab("Cập Nhật", pnl_CapNhat);

        pnl_Danhsach.setBackground(new java.awt.Color(255, 255, 255));

        tbl_Nguoihoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_Nguoihoc.setForeground(new java.awt.Color(102, 102, 102));
        tbl_Nguoihoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MÃ NH", "HỌ VÀ TÊN", "GIỚI TÍNH", "NGÀY SINH", "ĐIỆN THOẠI", "EMAIL", "NHÂN VIÊN", "NGÀY ĐK"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Nguoihoc.setRowHeight(22);
        tbl_Nguoihoc.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_Nguoihoc.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_Nguoihoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_NguoihocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Nguoihoc);

        txt_Timkiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_Timkiem.setForeground(new java.awt.Color(255, 102, 102));
        txt_Timkiem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_TimkiemCaretUpdate(evt);
            }
        });
        txt_Timkiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_TimkiemFocusGained(evt);
            }
        });

        lbl_Search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Search.setForeground(new java.awt.Color(102, 102, 102));
        lbl_Search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Search.setText("SEARCH");

        javax.swing.GroupLayout pnl_DanhsachLayout = new javax.swing.GroupLayout(pnl_Danhsach);
        pnl_Danhsach.setLayout(pnl_DanhsachLayout);
        pnl_DanhsachLayout.setHorizontalGroup(
            pnl_DanhsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_DanhsachLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnl_DanhsachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Timkiem)
                .addContainerGap())
        );
        pnl_DanhsachLayout.setVerticalGroup(
            pnl_DanhsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_DanhsachLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnl_DanhsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE))
        );

        tabs.addTab("Danh Sách", pnl_Danhsach);

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(tabs)
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabs))
        );

        add(pnl1, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        this.insert();
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_MoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MoiActionPerformed
        // TODO add your handling code here:
        this.clearForm();
    }//GEN-LAST:event_btn_MoiActionPerformed

    private void tbl_NguoihocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_NguoihocMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            this.row = tbl_Nguoihoc.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tbl_NguoihocMouseClicked

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_FirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FirstActionPerformed
        // TODO add your handling code here:
        this.first();
    }//GEN-LAST:event_btn_FirstActionPerformed

    private void btn_PrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrevActionPerformed
        // TODO add your handling code here:
        this.prev();
    }//GEN-LAST:event_btn_PrevActionPerformed

    private void btn_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NextActionPerformed
        // TODO add your handling code here:
        this.next();
    }//GEN-LAST:event_btn_NextActionPerformed

    private void btn_LastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LastActionPerformed
        // TODO add your handling code here:
        this.last();
    }//GEN-LAST:event_btn_LastActionPerformed

    private void txt_TimkiemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_TimkiemCaretUpdate
        // TODO add your handling code here:
        this.search();
    }//GEN-LAST:event_txt_TimkiemCaretUpdate

    private void txt_TimkiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_TimkiemFocusGained
        // TODO add your handling code here:
        txt_Timkiem.setText("");
    }//GEN-LAST:event_txt_TimkiemFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NguoiHoc_Dialog dialog = new NguoiHoc_Dialog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_First;
    private javax.swing.JButton btn_Last;
    private javax.swing.JButton btn_Moi;
    private javax.swing.JButton btn_Next;
    private javax.swing.JButton btn_Prev;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_Dienthoai;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_HoTen;
    private javax.swing.JLabel lbl_MaNH;
    private javax.swing.JLabel lbl_Ngaysinh;
    private javax.swing.JLabel lbl_Search;
    private javax.swing.JLabel lbl_ghichu;
    private javax.swing.JLabel lbl_gioitinh;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl_CapNhat;
    private javax.swing.JPanel pnl_Danhsach;
    private javax.swing.JRadioButton rdo_Nam;
    private javax.swing.JRadioButton rdo_Nu;
    private javax.swing.JSeparator spr2;
    private javax.swing.JSeparator spr3;
    private javax.swing.JSeparator spr4;
    private javax.swing.JSeparator spr5;
    private javax.swing.JSeparator spr6;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tbl_Nguoihoc;
    private javax.swing.JTextField txt_Dienthoai;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextArea txt_Ghichu;
    private javax.swing.JTextField txt_Hoten;
    private javax.swing.JTextField txt_MaNH;
    private javax.swing.JTextField txt_Ngaysinh;
    private javax.swing.JTextField txt_Timkiem;
    // End of variables declaration//GEN-END:variables

    NguoiHocDAO dao = new NguoiHocDAO();
    int row = -1;

    private void init() {
        //chuyển Dialog ra giữa
        this.setLocationRelativeTo(null);
        //gọi hàm tạo icon tiêu đề cho Dialog
        this.setIconImage(XImage.getAppIcon());
        this.fillTable();
        this.row = -1;
        this.updateStatus();
        clearForm();
    }

    private void fillTable() {
        DefaultTableModel dtm = (DefaultTableModel) tbl_Nguoihoc.getModel();
        dtm.setRowCount(0);
        try {
            String key = txt_Timkiem.getText();
            List<NguoiHoc> list = dao.selectByKeyword(key);
            for (NguoiHoc nh : list) {
                Object[] row = {nh.getMaNH(), nh.getHoTen(), nh.isGioiTinh() ? "Nam" : "Nữ", XDate.toString(nh.getNgaySinh(), "dd/MM/yyyy"), nh.getDienThoai(), nh.getEmail(), nh.getMaNV(), XDate.toString(nh.getNgayDK(), "dd/MM/yyyy")};
                dtm.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.warning(this, "Lỗi Truy Vấn Dữ Liệu !");
        }
    }

    private void setForm(NguoiHoc nh) {
        txt_MaNH.setText(nh.getMaNH());
        txt_Hoten.setText(nh.getHoTen());
        txt_Ngaysinh.setText(XDate.toString(nh.getNgaySinh(), "dd/MM/yyyy"));
        txt_Dienthoai.setText(nh.getDienThoai());
        txt_Email.setText(nh.getEmail());
        txt_Ghichu.setText(nh.getGhiChu());
        rdo_Nam.setSelected(nh.isGioiTinh());
        rdo_Nu.setSelected(!nh.isGioiTinh());
    }

    NguoiHoc getForm() {
        NguoiHoc nh = new NguoiHoc();
        nh.setMaNH(txt_MaNH.getText());
        nh.setHoTen(txt_Hoten.getText());
        nh.setGioiTinh(rdo_Nam.isSelected());
        nh.setNgaySinh(XDate.toDate(txt_Ngaysinh.getText(), "dd/MM/yyyy"));
        nh.setDienThoai(txt_Dienthoai.getText());
        nh.setEmail(txt_Email.getText());
        nh.setGhiChu(txt_Ghichu.getText());
        nh.setMaNV(Auth.user.getMaNV());
        nh.setNgayDK(nh.getNgayDK());
        return nh;
    }

    private void clearForm() {
        NguoiHoc nh = new NguoiHoc();
        this.setForm(nh);
        txt_Ngaysinh.setText("00/00/0000");
        this.row = -1;
        this.updateStatus();
    }

    private void insert() {
        NguoiHoc nh = getForm();
        String id = txt_MaNH.getText();
        String ten = txt_Hoten.getText();
        String dt = txt_Dienthoai.getText();
        String email = txt_Email.getText();
        String ghichu = txt_Ghichu.getText();
        boolean check = rdo_Nam.isSelected() || rdo_Nu.isSelected();
        if (!Auth.isManager()) {
            MsgBox.warning(this, "Bạn Không Thể Thêm Người Học !");
        } else if (id.equals("") || ten.equals("") || dt.equals("") || email.equals("") || ghichu.equals("")) {
            MsgBox.warning(this, "Thông Tin Người Học Còn Trống !");
        } else if (!check) {
            MsgBox.warning(this, "Vui Lòng Chọn Giới Tính !");
        } else {
            try {
                dao.insert(nh);
                this.fillTable();
                this.clearForm();
                MsgBox.alert(this, "Thêm Thành Công");
            } catch (Exception e) {
                MsgBox.warning(this, "Thêm Thất Bại !\nĐã Trùng Mã Người Học !");
            }
        }
    }

    private void update() {
        NguoiHoc nh = getForm();
        try {
            dao.update(nh);
            this.fillTable();
            MsgBox.alert(this, "Cập Nhật Thành Công");
        } catch (Exception e) {
            MsgBox.warning(this, "Cập Nhật Thất Bại !");
        }
    }

    private void delete() {
        if (!Auth.isManager()) {
            MsgBox.warning(this, "Bạn Không Có Quyền Xóa Người Học !");
        } else {
            if (MsgBox.confirm(this, "Xóa Người Học Này ?")) {
                String maNH = txt_MaNH.getText();
                try {
                    dao.delete(maNH);
                    this.fillTable();
                    this.clearForm();
                    MsgBox.alert(this, "Xóa Thành Công");
                } catch (Exception e) {
                    MsgBox.warning(this, "Xóa Thất Bại !");
                }
            }
        }
    }

    private void edit() {
        String maNH = (String) tbl_Nguoihoc.getValueAt(row, 0);
        NguoiHoc nh = dao.selectById(maNH);
        this.setForm(nh);
        tabs.setSelectedIndex(0);
        this.updateStatus();
    }

    private void first() {
        this.row = 0;
        this.edit();
    }

    private void prev() {
        if (this.row > 0) {
            this.row--;
            this.edit();
        }
    }

    private void next() {
        if (this.row < tbl_Nguoihoc.getRowCount() - 1) {
            this.row++;
            this.edit();
        }
    }

    private void last() {
        this.row = tbl_Nguoihoc.getRowCount() - 1;
        this.edit();
    }

    private void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tbl_Nguoihoc.getRowCount() - 1);
        //trạng thai form
        txt_MaNH.setEditable(!edit);
        btn_Them.setEnabled(!edit);
        btn_Sua.setEnabled(edit);
        btn_Xoa.setEnabled(edit);
        //trạng thái diều hướng
        btn_First.setEnabled(edit && !first);
        btn_Prev.setEnabled(edit && !first);
        btn_Next.setEnabled(edit && !last);
        btn_Last.setEnabled(edit && !last);
    }

    private void search() {
        this.fillTable();
        this.clearForm();
        this.row = -1;
        this.updateStatus();
    }
}
