/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import DAO.NhanVienDAO;
import Entity.NhanVien;
import Utils.Auth;
import Utils.MsgBox;
import Utils.XImage;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vietm
 */
public class NhanVien_Dialog extends java.awt.Dialog {

    /**
     * Creates new form NhanVien_Dialog
     */
    public NhanVien_Dialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbl_Text = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        pnl_Capnhat = new javax.swing.JPanel();
        lbl_MaNV = new javax.swing.JLabel();
        txt_MaNV = new javax.swing.JTextField();
        spr4 = new javax.swing.JSeparator();
        lbl_MK = new javax.swing.JLabel();
        spr5 = new javax.swing.JSeparator();
        lbl_XNMK = new javax.swing.JLabel();
        spr6 = new javax.swing.JSeparator();
        lbl_Hoten = new javax.swing.JLabel();
        txt_Hoten = new javax.swing.JTextField();
        spr7 = new javax.swing.JSeparator();
        lbl_Hoten1 = new javax.swing.JLabel();
        rdo_Nhanvien = new javax.swing.JRadioButton();
        rdo_TruongPhong = new javax.swing.JRadioButton();
        btn_Them = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Moi = new javax.swing.JButton();
        btn_Last = new javax.swing.JButton();
        btn_Next = new javax.swing.JButton();
        btn_Prev = new javax.swing.JButton();
        btn_First = new javax.swing.JButton();
        txt_Matkhau = new javax.swing.JPasswordField();
        txt_Matkhau1 = new javax.swing.JPasswordField();
        pnl_Danhsach = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Nhanvien = new javax.swing.JTable();

        setTitle("EduSys - QUẢN LÝ NHÂN VIÊN");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbl_Text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Text.setForeground(new java.awt.Color(102, 102, 102));
        lbl_Text.setText("QUẢN LÝ NHÂN VIÊN QUẢN TRỊ");
        lbl_Text.setToolTipText("");

        tabs.setBackground(new java.awt.Color(255, 255, 255));
        tabs.setForeground(new java.awt.Color(255, 102, 102));
        tabs.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        pnl_Capnhat.setBackground(new java.awt.Color(255, 255, 255));

        lbl_MaNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_MaNV.setForeground(new java.awt.Color(102, 102, 102));
        lbl_MaNV.setText("Mã Nhân Viên");

        txt_MaNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_MaNV.setForeground(new java.awt.Color(255, 102, 102));
        txt_MaNV.setBorder(null);

        spr4.setBackground(new java.awt.Color(102, 102, 102));
        spr4.setForeground(new java.awt.Color(102, 102, 102));

        lbl_MK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_MK.setForeground(new java.awt.Color(102, 102, 102));
        lbl_MK.setText("Mật Khẩu");

        spr5.setBackground(new java.awt.Color(102, 102, 102));
        spr5.setForeground(new java.awt.Color(102, 102, 102));

        lbl_XNMK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_XNMK.setForeground(new java.awt.Color(102, 102, 102));
        lbl_XNMK.setText("Xác Nhận Mật Khẩu");

        spr6.setBackground(new java.awt.Color(102, 102, 102));
        spr6.setForeground(new java.awt.Color(102, 102, 102));

        lbl_Hoten.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Hoten.setForeground(new java.awt.Color(102, 102, 102));
        lbl_Hoten.setText("Họ Và Tên");

        txt_Hoten.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_Hoten.setForeground(new java.awt.Color(255, 102, 102));
        txt_Hoten.setBorder(null);

        spr7.setBackground(new java.awt.Color(102, 102, 102));
        spr7.setForeground(new java.awt.Color(102, 102, 102));

        lbl_Hoten1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Hoten1.setForeground(new java.awt.Color(102, 102, 102));
        lbl_Hoten1.setText("Vai Trò");

        rdo_Nhanvien.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdo_Nhanvien);
        rdo_Nhanvien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdo_Nhanvien.setForeground(new java.awt.Color(102, 102, 102));
        rdo_Nhanvien.setText("Nhân Viên");

        rdo_TruongPhong.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdo_TruongPhong);
        rdo_TruongPhong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdo_TruongPhong.setForeground(new java.awt.Color(102, 102, 102));
        rdo_TruongPhong.setText("Trưởng Phòng");

        btn_Them.setBackground(new java.awt.Color(102, 102, 102));
        btn_Them.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Them.setForeground(new java.awt.Color(255, 255, 255));
        btn_Them.setText("Thêm");
        btn_Them.setBorder(null);
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Sua.setBackground(new java.awt.Color(102, 102, 102));
        btn_Sua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_Sua.setText("Sửa");
        btn_Sua.setBorder(null);
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Xoa.setBackground(new java.awt.Color(102, 102, 102));
        btn_Xoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_Xoa.setText("Xóa");
        btn_Xoa.setBorder(null);
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_Moi.setBackground(new java.awt.Color(102, 102, 102));
        btn_Moi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Moi.setForeground(new java.awt.Color(255, 255, 255));
        btn_Moi.setText("Mới");
        btn_Moi.setBorder(null);
        btn_Moi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MoiActionPerformed(evt);
            }
        });

        btn_Last.setBackground(new java.awt.Color(102, 102, 102));
        btn_Last.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Last.setForeground(new java.awt.Color(255, 255, 255));
        btn_Last.setText(">|");
        btn_Last.setBorder(null);
        btn_Last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LastActionPerformed(evt);
            }
        });

        btn_Next.setBackground(new java.awt.Color(102, 102, 102));
        btn_Next.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Next.setForeground(new java.awt.Color(255, 255, 255));
        btn_Next.setText(">>");
        btn_Next.setBorder(null);
        btn_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NextActionPerformed(evt);
            }
        });

        btn_Prev.setBackground(new java.awt.Color(102, 102, 102));
        btn_Prev.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Prev.setForeground(new java.awt.Color(255, 255, 255));
        btn_Prev.setText("<<");
        btn_Prev.setBorder(null);
        btn_Prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrevActionPerformed(evt);
            }
        });

        btn_First.setBackground(new java.awt.Color(102, 102, 102));
        btn_First.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_First.setForeground(new java.awt.Color(255, 255, 255));
        btn_First.setText("|<");
        btn_First.setBorder(null);
        btn_First.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FirstActionPerformed(evt);
            }
        });

        txt_Matkhau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_Matkhau.setForeground(new java.awt.Color(255, 102, 102));
        txt_Matkhau.setBorder(null);

        txt_Matkhau1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_Matkhau1.setForeground(new java.awt.Color(255, 102, 102));
        txt_Matkhau1.setBorder(null);

        javax.swing.GroupLayout pnl_CapnhatLayout = new javax.swing.GroupLayout(pnl_Capnhat);
        pnl_Capnhat.setLayout(pnl_CapnhatLayout);
        pnl_CapnhatLayout.setHorizontalGroup(
            pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(rdo_TruongPhong)
                        .addGap(105, 105, 105)
                        .addComponent(rdo_Nhanvien)
                        .addContainerGap(113, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_CapnhatLayout.createSequentialGroup()
                        .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Matkhau)
                            .addComponent(txt_MaNV)
                            .addComponent(spr4)
                            .addComponent(spr5)
                            .addComponent(spr6)
                            .addComponent(txt_Hoten)
                            .addComponent(spr7)
                            .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                                .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_MaNV)
                                    .addComponent(lbl_MK)
                                    .addComponent(lbl_XNMK)
                                    .addComponent(lbl_Hoten)
                                    .addComponent(lbl_Hoten1))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                                .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Moi, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_First, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Prev, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Last, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_Matkhau1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        pnl_CapnhatLayout.setVerticalGroup(
            pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CapnhatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_MaNV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(spr4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_MK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spr5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_XNMK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Matkhau1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spr6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Hoten)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(spr7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Hoten1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdo_TruongPhong)
                    .addComponent(rdo_Nhanvien))
                .addGap(18, 18, 18)
                .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_First, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Prev, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Last, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_CapnhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Moi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tabs.addTab("Cập Nhật", pnl_Capnhat);

        pnl_Danhsach.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Danhsach.setLayout(new java.awt.BorderLayout());

        tbl_Nhanvien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_Nhanvien.setForeground(new java.awt.Color(102, 102, 102));
        tbl_Nhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Mật Khẩu", "Họ Và Tên", "Vai Trò"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Nhanvien.setRowHeight(22);
        tbl_Nhanvien.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_Nhanvien.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_Nhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_NhanvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Nhanvien);

        pnl_Danhsach.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        tabs.addTab("Danh Sách", pnl_Danhsach);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Text)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(tabs)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_Text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void tbl_NhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_NhanvienMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            this.row = tbl_Nhanvien.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tbl_NhanvienMouseClicked

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        this.insert();
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_MoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MoiActionPerformed
        // TODO add your handling code here:
        this.clearForm();
    }//GEN-LAST:event_btn_MoiActionPerformed

    private void btn_FirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FirstActionPerformed
        // TODO add your handling code here:
        this.first();
    }//GEN-LAST:event_btn_FirstActionPerformed

    private void btn_PrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrevActionPerformed
        // TODO add your handling code here:
        this.prev();
    }//GEN-LAST:event_btn_PrevActionPerformed

    private void btn_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NextActionPerformed
        // TODO add your handling code here:
        this.next();
    }//GEN-LAST:event_btn_NextActionPerformed

    private void btn_LastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LastActionPerformed
        // TODO add your handling code here:
        this.last();
    }//GEN-LAST:event_btn_LastActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NhanVien_Dialog dialog = new NhanVien_Dialog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_First;
    private javax.swing.JButton btn_Last;
    private javax.swing.JButton btn_Moi;
    private javax.swing.JButton btn_Next;
    private javax.swing.JButton btn_Prev;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Hoten;
    private javax.swing.JLabel lbl_Hoten1;
    private javax.swing.JLabel lbl_MK;
    private javax.swing.JLabel lbl_MaNV;
    private javax.swing.JLabel lbl_Text;
    private javax.swing.JLabel lbl_XNMK;
    private javax.swing.JPanel pnl_Capnhat;
    private javax.swing.JPanel pnl_Danhsach;
    private javax.swing.JRadioButton rdo_Nhanvien;
    private javax.swing.JRadioButton rdo_TruongPhong;
    private javax.swing.JSeparator spr4;
    private javax.swing.JSeparator spr5;
    private javax.swing.JSeparator spr6;
    private javax.swing.JSeparator spr7;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tbl_Nhanvien;
    private javax.swing.JTextField txt_Hoten;
    private javax.swing.JTextField txt_MaNV;
    private javax.swing.JPasswordField txt_Matkhau;
    private javax.swing.JPasswordField txt_Matkhau1;
    // End of variables declaration//GEN-END:variables

    NhanVienDAO dao = new NhanVienDAO();

    int row = -1;

    private void init() {
        //chuyển Dialog ra giữa
        this.setLocationRelativeTo(null);
        //gọi hàm tạo icon tiêu đề cho Dialog
        this.setIconImage(XImage.getAppIcon());
        this.fillTable();
        this.row = -1;
        this.updateStatus();
        this.clearForm();
    }

    private void insert() {
        NhanVien nv = getForm();
        String mk1 = new String(txt_Matkhau1.getPassword());
        String maNV = txt_MaNV.getText();
        String mk = new String(txt_Matkhau.getPassword());
        String hoTen = txt_Hoten.getText();
        boolean check = rdo_TruongPhong.isSelected() || rdo_Nhanvien.isSelected();
        if (!Auth.isManager()) {
            MsgBox.warning(this, "Bạn Không Thể Thêm Nhân Viên !");
        } else if (!mk1.equals(nv.getMatKhau())) {
            MsgBox.warning(this, "Xác Nhận Mật Khẩu Không Đúng !");
        } else if (maNV.equals("") || mk.equals("") || hoTen.equals("")) {
            MsgBox.warning(this, "Thông Tin Nhân Viên Còn Trống !");
        } else if (!check) {
            MsgBox.warning(this, "Vui Lòng Chọn Vai Trò !");
        } else {
            try {
                dao.insert(nv);
                this.fillTable();
                this.clearForm();
                MsgBox.alert(this, "Thêm Thành Công");
            } catch (Exception e) {
                MsgBox.warning(this, "Thêm Thất Bại !\nVui Lòng Kiểm Tra Lại Mã Nhân Viên !");
            }
        }
    }

    private void update() {
        NhanVien nv = getForm();
        String mk1 = new String(txt_Matkhau1.getPassword());
        if (!mk1.equals(nv.getMatKhau())) {
            MsgBox.warning(this, "Xác Nhận Mật Khẩu Không Đúng !");
        } else {
            try {
                dao.update(nv);
                this.fillTable();
                MsgBox.alert(this, "Cập Nhật Thành Công");
            } catch (Exception e) {
                MsgBox.warning(this, "Cập Nhật Thất Bại !");
            }
        }
    }

    private void delete() {
        if (!Auth.isManager()) {
            MsgBox.warning(this, "Bạn Không Có Quyền Xóa Nhân Viên !");
        } else {
            String manv = txt_MaNV.getText();
            if (manv.equals(Auth.user.getMaNV())) {
                MsgBox.warning(this, "Không Thể Xóa Chính Bạn !");
            } else if (MsgBox.confirm(this, "Xóa Nhân Viên Này ?")) {
                try {
                    dao.delete(manv);
                    this.fillTable();
                    this.clearForm();
                    MsgBox.alert(this, "Xóa Thành Công !");
                } catch (Exception e) {
                    MsgBox.warning(this, "Xóa Thất Bại !");
                }
            }
        }
    }

    private void clearForm() {
        NhanVien nv = new NhanVien();
        this.setForm(nv);
        this.row = -1;
        this.updateStatus();
    }

    private void edit() {
        String manv = (String) tbl_Nhanvien.getValueAt(this.row, 0);
        NhanVien nv = dao.selectById(manv);
        this.setForm(nv);
        tabs.setSelectedIndex(0);
        this.updateStatus();
    }

    private void first() {
        this.row = 0;
        this.edit();
    }

    private void prev() {
        if (this.row > 0) {
            this.row--;
            this.edit();
        }
    }

    private void next() {
        if (this.row < tbl_Nhanvien.getRowCount() - 1) {
            this.row++;
            this.edit();
        }
    }

    private void last() {
        this.row = tbl_Nhanvien.getRowCount() - 1;
        this.edit();
    }

    private void fillTable() {
        DefaultTableModel dtm = (DefaultTableModel) tbl_Nhanvien.getModel();
        dtm.setRowCount(0); //xóa tất cả hàng trên table
        try {
            List<NhanVien> list = dao.selectAll(); //đọc data từ SQL
            for (NhanVien nv : list) {
                Object[] row = {nv.getMaNV(), "--Không Thể Xem--", nv.getHoTen(), nv.isVaiTro() ? "Trưởng Phòng" : "Nhân Viên"
                };
                dtm.addRow(row);//thêm vào table 1 dòng
            }
        } catch (Exception e) {
            MsgBox.warning(this, "Lỗi Truy Vấn Dữ Liệu !");
        }
    }

    private void setForm(NhanVien nv) {
        txt_MaNV.setText(nv.getMaNV());
        txt_Hoten.setText(nv.getHoTen());
        txt_Matkhau.setText(nv.getMatKhau());
        txt_Matkhau1.setText(nv.getMatKhau());
        rdo_TruongPhong.setSelected(nv.isVaiTro());
        rdo_Nhanvien.setSelected(!nv.isVaiTro());
    }

    NhanVien getForm() {
        NhanVien nv = new NhanVien();
        nv.setMaNV(txt_MaNV.getText());
        nv.setHoTen(txt_Hoten.getText());
        nv.setMatKhau(new String(txt_Matkhau.getPassword()));
        nv.setVaiTro(rdo_TruongPhong.isSelected());
        return nv;
    }

    private void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tbl_Nhanvien.getRowCount() - 1);
        //trạng thai form
        txt_MaNV.setEditable(!edit);
        btn_Them.setEnabled(!edit);
        btn_Sua.setEnabled(edit);
        btn_Xoa.setEnabled(edit);
        //trạng thái diều hướng
        btn_First.setEnabled(edit && !first);
        btn_Prev.setEnabled(edit && !first);
        btn_Next.setEnabled(edit && !last);
        btn_Last.setEnabled(edit && !last);
    }
}
